### ISSUE TITLE
lobid-resources is down

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#1078]
The lobid-resources index seems to be down and as one effect NWBib is not working as well. Example queries:

- https://lobid.org/resources/search?q=bibliothek with error message:

![image](https://user-images.githubusercontent.com/160292/95998273-ff585780-0e34-11eb-8cea-dd02bb7a95cc.png)

- https://nwbib.de/search?q=bibliothek (no results and no error message)

**Comment by acka47** [comment]
lobid-gnd and -organisations are fine. I don't get any emails (nagios or other) with regard to lobid-resources.

**Comment by dr0i** [comment]
These IPs (pointing to ES-clusters) are not reachable from within the application server. Now there are two reasons:

1. the AP-Server has lost its second ethernet interface with the routing to the 10.9.0.* net
2. the config should has used the domain names instead and was somehow misconfigured

I have the feeling that 1. is true, although I couldn't find anything in the logs adhoc. And there *are* multiple NICs on the server. Also, I couldn't find traces that the conf/resources.conf was manipulated - it seems to be configed like this for months.

I will later investigate. For now, the easiest solution was two use the one interface and using domain names instead of ips.

**Comment by dr0i** [comment]
Uh, no, that was not the solution. It just seemed as it, must be the proxy. Will try than that proxy (stage).

**Comment by dr0i** [comment]
The proxied stage works, and its index is in nearly 100% sync with prod. NWBIB works also again. Will investigate tomorrow.

**Comment by dr0i** [comment]
Nearly 100% means exactly this, there is virtually no difference. Biggest impact is the later updating, daily updates will be ready at ~ 8:30 instead of 5:00 o'clock.

I wrote an email to IT because of the really strange network problem. Maybe they come up with a sane solution, otherwise I suggested to use a new/other NIC, plug cat-cable in/out or reboot switch.

**Comment by dr0i** [comment]
Configured to use the still reachable `weywot3`. So this is back to normal.
Re cause of the network trouble: IT says unknown.
Will open a new maintenance issue for this.
Closing this one.
