### ISSUE TITLE
Transform Alma MARC21 XML to lobid JSON-LD

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1089]
At some point in the future there will be no more Aleph and thus no more MAB XML as our primary data input. It will be substituted by Alma's MARC21 XML. The transition is a hybrid approach where both kinds of data are indexed into the same index.

Based on  https://github.com/hbz/limetrans/compare/alma provided by @blackwinter .

**Comment by dr0i** [comment]
Don't know if a PR should be opened. @acka47 see what's produced atm and if that would be reasonable enough to start a PR : https://github.com/hbz/lobid-resources/tree/almaMarc21XmlToLobidJson/src/test/resources/alma.

**Comment by acka47** [comment]
I think this already looks very good! A PR would be good I think. I think we should ASAP get this into a status where we can include this in lobid-resources so that @hagbeck can start testing and we have the possibility to have a few more iterations with Hans-Georg in the loop.

Some comments on the output data:
- As far as I can see without going deeper into it, only the metametadata needs some more work (`sourceOrganisation` etc.).
- Looking at https://github.com/hbz/lobid-resources/blob/b446f785ebc98b37ee41c300fc78e6b9462ed7fe/src/test/resources/alma/HT012734833.json#L5-L33 and https://github.com/hbz/lobid-resources/blob/b446f785ebc98b37ee41c300fc78e6b9462ed7fe/src/test/resources/alma/KUR00770801.json#L6-L13 I see it is indicated with `heldBy` that an organization has obtained a license to access an online resource. This absolutely makes sense as we don't have to adjust our data model for licensed online resources and lobid users will presumably be able to cover all the use cases with this approach.
- We should also check out the Bibframe RDF that Alma provides for the resources. It might give us some ideas on what is missing or what might be handled in another way.

**Comment by dr0i** [comment]
I would say we go to close this issue.
Opened #1095. Go on opening new issues  when identified.
Ok @acka47 ?

**Comment by acka47** [comment]
+1
