### ISSUE TITLE
Index Alma Marc Xml into ES

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1102]
We need a database which is  in (daily updated) sync with  Alma's Marc Xml publishing.
Idea is to reuse https://github.com/hbz/mabxml-elasticsearch/ .

**Comment by dr0i** [comment]
@blackwinter has proposed an other way to do this, involving Berkley DB and the filesystem. As discussed with the OI-Team we should maybe consolidate these coming tools (if possible) or they may complement each other. Either way, we should keep an eye on each other, probably by code reviewing each other to be up to date.

**Comment by blackwinter** [comment]
The plan is to support indexing (sequential read) with first priority and record retrieval (random read) distinctly second. Elasticsearch, however, optimizes for the latter over the former (not to mention the operational overhead).

As of now¹, data will be kept in compressed files on the file system, in particular, [Blocked GNU Zip Format (BGZF)](https://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html) will be used. It's Gzip-compatible, so existing indexing pipelines remain unchanged. At the same time, it allows for sufficiently fast random access (which will be wrapped in a web front end/API).

In order to store the data record's BGZF offsets as well as additional metadata, [Lightning Memory-Mapped Database (LMDB)](https://symas.com/lmdb/) will be employed.

Both formats have binary-compatible implementations in Ruby and Java (among others), which is crucial for potential future features/workflows built on top of this data store.

¹ Let's hope we won't have to change plans yet again ;)

**Comment by dr0i** [comment]
Thx @blackwinter for providing this !
 Havent' tried to load the data using BGZF on the file, but the API works like a charm, e.g.:
https://indexes.devel.digibib.net/export/990197023370206441
Closing.
