### ISSUE TITLE
Multiple persons typed as being the same person

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#1141]
See
https://github.com/hbz/lobid-resources/blob/master/src/test/resources/alma/HT005207972.json#L60.

**Comment by TobiasNx** [comment]
It seems that the data is coming from:

https://github.com/hbz/lobid-resources/blob/0fdbc084f7cb24186c885079d0005ac7478a10ed/src/test/resources/alma/HT005207972.xml#L47

There are a lot of different sources of contributer/creator-information:
1)
https://github.com/hbz/lobid-resources/blob/0fdbc084f7cb24186c885079d0005ac7478a10ed/src/main/resources/alma/common/fields.xml#L267

2)
https://github.com/hbz/lobid-resources/blob/0fdbc084f7cb24186c885079d0005ac7478a10ed/src/main/resources/alma/common/fields.xml#L157

3)
https://github.com/hbz/lobid-resources/blob/0fdbc084f7cb24186c885079d0005ac7478a10ed/src/main/resources/alma/common/fields.xml#L190

Also we have a standalone mapping file:

4)
https://github.com/hbz/lobid-resources/blob/master/src/main/resources/alma/common/personCreator.xml


I think 245 should not be the source for our creator information:
https://www.loc.gov/marc/bibliographic/bd245.html

I also think that we should rearrange our creator information-mapping. Is 4) used?

**Comment by dr0i** [comment]
- `245.c` is "Statement of responsibility, etc.", so in principle this seems good. But it seems a bit unstructured and one doesn't know what to expect when using this field (re: mutiple persons). So let us dump that field, especially as it seems to be covered by other , more structured fields.
- `personCreator.xml` seems indeed not to be used, but its content (all?) seems to be copied into `fields.xml. Don't know - we may use  `personCreator.xml` to separate concerns - yes seems to be better.

**Comment by TobiasNx** [comment]
I will move all contribution-metadata to submorph contribution-xml:
100/110 include the most creator informations while 700/710 additional creator and other contributors.
245c would not be needed then.

Also I intend to introduce following changes:

- [ ] Delete 245.c since it is a subfield of MARC-field 245 Title Statement which does not provide additional information as MARC 100/110 or 700/710. 
- [ ] Combine workflows that map 100 and 700 as is already used for CoproreBodies
- [ ] Add label Family for Indicator 3, if at all used? Should then also be allowed in the Schema
- [ ] Allow more roles
- [ ] And use the macro's that are mostly outcommeted

**Comment by dr0i** [comment]
Great :)
Deployed, see http://alma.lobid.org/resources/search?q=HT005207972&format=json.
Closing.
