### ISSUE TITLE
enrich ISBNs (Alma)

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1180]
Currently Alma exports only the ISBNs which are in the origin MARC record. 

Please use morph functions `<isbn to="isbn10"/>` and `<isbn to="isbn13"/>` to ensure that both versions of ISBNs find their way in the lobid-resources.

Example: http://alma.lobid.org/resources/990030520380206441.json

**Comment by dr0i** [comment]
If an isbn10 exists a corresponding isbn13 is generated.
    Also, an isbn is normalized by removing semnatic sugar, so that:
    
    -  "isbn" : [ "3-642-32079-1" ],
    +  "isbn" : [ "3642320791", "9783642320798" ],

Going to deploy.

**Comment by dr0i** [comment]
Deployed, see e.g. https://github.com/hbz/lobid-resources/pull/1184.
Closing.

**Comment by dr0i** [comment]
https://github.com/hbz/lobid-resources/pull/1184/commits/c6e59ec999bb40e3249a95238498e90d56e6cb09 introduced duplicate isbns. This cannot be seen in the test data (https://github.com/hbz/lobid-resources/blob/master/src/test/resources/alma/(DE-605)HT019246898.json) but in the new index (http://alma.lobid.org/resources/search?q=HT019246898&format=json). That's because the tests are not working atm (see https://github.com/hbz/lobid-resources/issues/1124) and we have to check  manually by doing a ` mvn failsafe:integration-test -Dit.test=AlmaMarc21XmlToLobidJsonTest; git diff`.
Reopened.

**Comment by TobiasNx** [comment]
I assume that the source data already has ISBN-10 and ISBN-13. It would make sense to add the `<unique />`-function at the end of each transformation.
Also this seems not to be a problem of the testing but of working multiple branches at the same time. The test file you refer to (https://github.com/hbz/lobid-resources/blob/master/src/test/resources/alma/(DE-605)HT019246898.json) does not exist in the 1180-enrichIsbn branch. It was introduced in the  1171-incorrectCurrentLocation. (https://github.com/hbz/lobid-resources/commits/master/src/test/resources/alma/(DE-605)HT019246898.json)

Due to the merging of multiple PRs at the same time the test data does not reflect all changes but only those that are pushed with the specific branches. Perhaps we should update the testfile after merging the master in the feature branch before merging the PR.

**Comment by TobiasNx** [comment]
I updated the morph and open a PR now.

**Comment by dr0i** [comment]
Indeed, the test resource HT019246898.json was added at a later stage. It proves to be a very good test case also for isbn, because this test case (a resource having both, isbn10 and isbn13) was not present before.

> Due to the merging of multiple PRs at the same time the test data does not reflect all changes ... Perhaps we should update the testfile after merging the master in the feature branch before merging the PR.

Yes, in this case it's true (working tests would come in handy here ;) ).

**Comment by dr0i** [comment]
Deployed, see http://alma.lobid.org/resources/search?q=HT019246898&format=json. Closed.
