### ISSUE TITLE
Add subject locations

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#130]
Data 2.0 contains no subject locations yet.

We will need subject locations to switch NWBib search to the new API, see https://github.com/hbz/nwbib/issues/262.

We might want to use the approach from lobid-organisations, based on the Mapzen API, see [1]. 

[1] https://github.com/hbz/lobid-organisations/commit/25bb79b370ca86e769f544bbb4be5e750d2c1934

**Comment by acka47** [comment]
Currently, we have the label and the geo coordinates in different fields not associated which each other, e.g.:

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "coverage" : "Köln",
  "subjectLocation" : "50.942222222222,6.9577777777778"
}
```

We should think to add subject location as an object in API 2.0. For example somethin like:

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "subjectLocation" : {
    "type": "Location",
    "lat": 50.942222222222,
    "lon": 6.9577777777778,
    "label": "Köln"  
    }
}
```

**Comment by fsteeg** [comment]
We will have to group the coordinates in some way for Elasticsearch support, e.g.

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "dct:spatial" : {
    "type": "Location",
    "location": "50.942222222222, 6.9577777777778",
    "label": "Köln"  
    }
}
```

See https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html

**Comment by acka47** [comment]
> We will have to group the coordinates in some way for Elasticsearch support

I generally would not have a problem with this but I wonder how we do geo queries with Elasticsearch for the OER World Map. There, we use the schema.org way of recording geo coordinates, e.g.:

```json
"location":{
   "geo":{
      "lon":6.935572,
      "lat":50.934119
   }
}
```

@literarymachine, can you shed some light on this?

**Comment by fsteeg** [comment]
Yes, that's another way to group them, as described in:
https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html

**Comment by acka47** [comment]
Ah, ok, then we will do it like we do it in the World Map and also in lobid-organisations:

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "dct:spatial" : {
    "type": "Location",
    "geo": {
      "lat": 50.942222222222,
      "lon": 6.9577777777778
    },
    "label": "Köln"  
    }
}
```

**Comment by acka47** [comment]
I made a file with all unique values of the `coverage` field. It can be found at 

1. `curl --header "Accept-Encoding: gzip" "http://lobid.org/resources/search?q=coverage:*+AND+inCollection.label:NWBib&format=bulk" > nwbib-coverage.gz`
2. unzip to nwbib-coverage.jsonl
3. `cat nwbib-coverage.jsonl | jq '.coverage[]' > nwbib-coverage-freetext`
4. `sort nwbib-coverage-freetext | uniq -c > nwbib-coverage_uniq_count.txt`

**Comment by acka47** [comment]
We decided to get the locations – as well as the information on hierarchies to create a classification – from wikidata. Thus, we should also add the wikidata URI:

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "dct:spatial" : {
    "type": "Location",
    "id": "http://www.wikidata.org/entity/Q365",
    "geo": {
      "type": "GeoCoordinates",
      "lat": 50.942222222222,
      "lon": 6.9577777777778
    },
    "label": "Köln"  
    }
}
```

**Comment by acka47** [comment]
FYI, you can get the wikidata subset for mapping NWBib free text to wikidata entities with this SPARQL query: http://tinyurl.com/y9a9g4sj

**Comment by acka47** [comment]
@dr0i When you build the elasticsearch index for the lookup, you should also include aliases as they are useful for the lookup. E.g. http://www.wikidata.org/entity/Q1759911, getting the JSON with `$ curl -L -H "Accept: application/json" https://www.wikidata.org/entity/Q1759911`. The aliases are provided like this:

```json
{
   "entities":{
      "Q1759911":{
         "aliases":{
            "de":[
               {
                  "language":"de",
                  "value":"Landkreis Rees"
               }
            ],
            "es":[
               {
                  "language":"es",
                  "value":"Kreis Rees"
               }
            ]
         }
      }
   }
}
```

**Comment by acka47** [comment]
> FYI, you can get the wikidata subset for mapping NWBib free text to wikidata entities with this SPARQL query: http://tinyurl.com/y9a9g4sj

There are a lot of entities repeated in the results. Here is the same query for distinct items: http://tinyurl.com/ya3v3bhk

**Comment by acka47** [comment]
By now, you can also get the labels & altLabels via SPARQL (it timed out when I first played around with these queries): http://tinyurl.com/yc2hz4bv

There are some items repeated (those which have > 1 altLabel). I tried to only list them once and to concatenate altLabels if there are more than one but failed. http://tinyurl.com/y7u66qwk doesn't work, maybe @dr0i finds a way to make it work...

**Comment by dr0i** [comment]
@acka47 It's totally sufficient to just have a list of entities using your sparql-query. These will be looked up one-by-one, getting all the labels and altLabels and whatnot.
Btw., you can already query the `geo-nwbib` index like this: `curl gaia.hbz-nrw.de:9200/geo-nwbib/_search?q=*`. Resource lookup is done like `curl gaia.hbz-nrw.de:9200/geo-nwbib/wikidata-geo/Q897382`.
Fyi, tweaked the geo coordinate parsing, now see:
` curl 'gaia.hbz-nrw.de:9200/geo-nwbib/_search?q=spatial.geo.lat:"0.0"'`
resulting in 

> "hits":{"total":458, ...

So there are `8230` distinct entities and `458` (or ~ 5%) of them lacking geo coordinates. Not so bad.

**Comment by dr0i** [comment]
The enrichment-work flows like this:
- get the `coverage` field from the resource
-  make a lookup in the `geo-nwbib` index using that string (boosted the `label` query with factor `100` in comparison to the the `alias`-array to get  better results)
- enrich the hbz01-resource if a hit could be resolved (using the `spatial` object)
-  index that resource.

Indexed small test set (~16k resources (includes items)).  There are around 102 `inCollection:NWBib` in there  (that's ~0.5%, which is ok (in hbz01 the relation is 0.3% (remember, WITH items!))). Out of these 102 exactly 74 now have the `spatial.geo` data. Thus, 28 have no geo-data, see for yourself : `$curl  'http://gaia.hbz-nrw.de:9200/nwbib-smalltest/_search?q=inCollection.label:NWBib%20AND%20_missing_:spatial.geo.lat'`.
We have to analyze why ~30% gets no coordinates.

**Comment by acka47** [comment]
We have to check how many of the resources that actually have a `coverage` field now have geo coordinates. Then the result is much better, see [http://gaia.hbz-nrw.de:9200/nwbib-smalltest/_search?q=inCollection.label:NWBib%20AND%20_missing_:spatial.geo.lat+AND+coverage:*](http://gaia.hbz-nrw.de:9200/nwbib-smalltest/_search?q=inCollection.label:NWBib%20AND%20_missing_:spatial.geo.lat+AND+coverage:*).

From the four entries with a `coverage` field and no geo coordinates two have encoding problems in the coverage field ("KÃ¶ln", "DÃ¼sseldorf"). Also, Münsterland" isn't mapped although its [wikidata entry](https://www.wikidata.org/wiki/Q1700) has the same label _and_ geo coordinates. The reason is that it is only of type [geographic region](https://www.wikidata.org/wiki/Q82794) (which, amongst others, is a sperclass of "administrative territorial entity") that is not covered by the SPARQL query above.

It makes sense to add all [entities that are only of type "geographic region" and located in NRW](http://tinyurl.com/y7a78vhf) as three more of those 17 entries can also be found in ''coverage'' ("Senne", "Niederrhein" and "Delbrücker Land"). Others from this list have their own notations in the current spatial classification (see http://nwbib.de/classification?t=Raumsystematik) and we will discuss what to do with those.

**Comment by acka47** [comment]
Another update to the SPARQL query: http://tinyurl.com/y8sbgcf5

Updates:
- removed "Verwaltungskooperationen"
- removed "Ämter" as they will be removed from coverage field anyway (see email by U. Pflughaupt to NWBib list from 2017-06-27)

**Comment by dr0i** [comment]
Added geo data into production index. http://lobid.org/resources/search?q=spatial.geo.lat:* .

**Comment by acka47** [comment]
The coverage of wikidata matches/geo coordinates is very good. From [292992 entries with a value in the `coverage` field](http://stage.lobid.org/resources/search?q=coverage:*) [287477 now have a link to wikidata ](http://stage.lobid.org/resources/search?q=spatial.id%3A*). This is a coverage of > 98 %!

Of these entries, [3230 are missing geo coordinates](http://stage.lobid.org/resources/search?q=spatial.id%3A*+AND+spatial.geo.lat:%220.0%22) because of the fact that wikidata doesn't have geo coordiantes for them yet.

However, the matching process doesn't seem to be very reliable as the quality of matches often is not good. We will have to improve this. Below some examples.

**Incorrect matches**

Here is a list of incorrect matches:
- http://stage.lobid.org/resources/HT017034736.json: "Monschauer Land" matched with ["Lüdenscheid-Land"](http://www.wikidata.org/entity/Q1880218)
- http://stage.lobid.org/resources/HT008408920.json: "Köln" matched with "[Köln-Rodenkirchen"](http://www.wikidata.org/entity/Q446716)
- http://stage.lobid.org/resources/HT017068756.json: "Petershagen <Minden-Lübbecke>" matched to ["Kreis Minden-Lübbecke"](http://www.wikidata.org/entity/Q6239)
- http://stage.lobid.org/resources/HT017125573.json: Wuppertal-Barmen" matched with ["Barmen (Jülich)"](http://www.wikidata.org/entity/Q808352)
- http://stage.lobid.org/resources/HT016189278.json: "Pyrmont <Grafschaft>" matched with [Grafschaft](http://www.wikidata.org/entity/Q1541594)
- http://stage.lobid.org/resources/HT003751388.json: "Eslohe (Sauerland)" matched with ["Sauerland"](http://www.wikidata.org/entity/Q4194)

**Multiple `coverage` values aren't mapped one by one**

Also, we don't take into account multiple values in the `coveragefield yet. See e.g. http://stage.lobid.org/resources/HT006934472.json which contains two values in `coverage`, "Düsseldorf <Nord>" and "Düsseldorf-Wittlaer". Although at least one of them has a separate wikidata entry ([Wittlaer](https://www.wikidata.org/wiki/Q881495)), "Düsseldorf" was added to the spatial field.

We should take into account that `coverage` can contain multiple values and accordingly use `spatial` with an array. Each value of `coverage` should be mapped individually. Will make a separate issue for this.

**Comment by acka47** [comment]
BTW, here is the former issue where we discussed wikidata lookup for NWBib locations: https://github.com/hbz/nwbib/issues/83

Out of curiosity, I sent the examples above to the Wikidata API and I am listing the first match here:

1. ["Monschauer Land"](https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Monschauer%20Land): [Monschauer Heckenland](https://www.wikidata.org/wiki/Q993449)
2. ["Köln"](https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Köln): [Köln](https://www.wikidata.org/wiki/Q365)
3. ["Petershagen <Minden-Lübbecke>"](https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Petershagen%20Minden-Lübbecke): [Petershagen](https://www.wikidata.org/wiki/Q182857)
4. ["Wuppertal-Barmen"](https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Wuppertal-Barmen): [Bahnhof Wuppertal-Barmen](https://www.wikidata.org/wiki/Q801637)
5. ["Pyrmont <Grafschaft>"](https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Pyrmont%20Grafschaft): [Grafschaft Pyrmont](https://www.wikidata.org/wiki/Q825489)
6. ["Eslohe (Sauerland)"](https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=Eslohe%20Sauerland): [Eslohe](https://www.wikidata.org/wiki/Q10929)

2., 3., 5. and 6. look very good. If we took the first result from the list that actually is on the list of administrative areas in NRW, we would also get correct results for 1. and 4., however, then we wouldn't get a result for 5.

@dr0i and me obviously had some misunderstandings in the past with the result that Pascal hasn't looked at the Wikidata API at all for this issue. Maybe we should reconsider using it as it obviously gives much better results than what we have right now.

**Comment by dr0i** [comment]
There are two separate parts o fthe programming:
1. building a geo-index (as cache and easy + fast merging)
2. merge that index into our resource documents

That's one of reasons I pledge to merge the PR, even if the geo coordinates aren't so good yet: improving the geodata is a separate part and subsequently possible. Will reopen a PR soon.

**Comment by acka47** [comment]
+1 for merging. I also discussed this with @fsteeg and he is ok with this approach. (Though he won't do any work on this when you are on holidays...)

**Comment by dr0i** [comment]
The api not always gives good results, e.g. https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=%20%20Freudenberg%20%20Siegen%20Wittgenstein hits a town nearby.
However, I think it's best to go two ways:
1. query the cache consisting of the set your SPARQL-query gaves us (around 8300. Out of these, ca 500 hadn't geo coordinates so were ignored).
2. As a fallback, if the internal cache lookup scores under a certain threshold, use the api lookup (and add the first hit to the internal cache)

**Comment by acka47** [comment]
Just talked to @fsteeg about the creation of the classification UI. For this, we will also need in the index the information from `wdt:P131` ("liegt in der Verwaltungseinheit") and `wdt:P150` ("Untereinheit (administrative Einheit)").

**Comment by acka47** [comment]
> The api not always gives good results, e.g. https://www.wikidata.org/w/api.php?action=query&list=search&format=json&srsearch=%20%20Freudenberg%20%20Siegen%20Wittgenstein hits a town nearby.

I [edited](https://www.wikidata.org/w/index.php?title=Q10946&type=revision&diff=563659536&oldid=528754602) the entry so that hopefully the correct location will soon come as first hit.

**Comment by acka47** [comment]
Here is an updated query that doesn't include "Stadtbezirke". (As far as I know they don't have them in NWBib.): http://tinyurl.com/y8rpexfm

```
# Get administrative areas (with some exemptions) in North Rhine-Westphalia with German labels

SELECT DISTINCT 
?item 
?itemLabel 
?partOf
(group_concat(distinct ?hasPart; separator = ", ") as ?parts)
WHERE {
  hint:Query hint:optimizer "None".
  { ?item wdt:P131* wd:Q1198;
        wdt:P31/wdt:P279* wd:Q387917 .
  }
  UNION
  {  ?item wdt:P131* wd:Q1198 ;
       wdt:P31 wd:Q82794 .
  }
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q192611 } # ohne Wahlkreise
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q20296613 } # Ohne Natur- und Landschaftsschutzgebiete
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q1643757 } # Ohne Landschaftsverbände
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q2520712 } # Ohne Verwaltungskooperationen 
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q478847 } # Ohne Ämter
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q2740635 } # Ohne Stadtbezirke
  SERVICE wikibase:label {  bd:serviceParam wikibase:language "de" }
  OPTIONAL { ?item wdt:P150 ?hasPart . }
  OPTIONAL { ?item wdt:P131 ?partOf }
}

GROUP BY ?item ?itemLabel ?parts ?partOf
```

**Comment by dr0i** [comment]
Deployed to staging, please have a look @acka47.
Notes:
- this has not yet incorporated your updated SPARQL query.
- multiple locations possible (json-array)
- seems to be better results now, but not perfect
- e.g. `Monschauer Land` hits without geo-coordinates => ignored.
- no success re: your update of `Freudenberg Kreis Siegen-Wittgenstein` (still stucks to `Bühl`)
- time for transformation (even with cache) increased to +18h! Will be faster next time because the cache "learned" about new entities (+3.000 (now in total ~11.000 ). Also discovered a lookup-bug which will improve performance.

**Comment by fsteeg** [comment]
Noticed one thing that seems odd: sometimes we have a nested `spatial.spatial` field, sometimes just `spatial`. See bottom of:

http://staging.lobid.org/resources/HT018244799.json
http://staging.lobid.org/resources/HT004217360.json

**Comment by acka47** [comment]
From [295,459 resources with content in the `coverage` field](http://staging.lobid.org/resources/search?q=coverage:*) only [17,950](http://staging.lobid.org/resources/search?q=coverage:*+AND+_missing_:spatial) are missing the `spatial` field. So, this is still quite a good coverage. I will take a deeper look at it as soon as I have more time.

**Comment by acka47** [comment]
Talking to @jimjonesbr this week, he pointed out that it would be important to add the reference system to the GeoCoordinates. This could be done using the [GeoSPARQL vocab](http://www.opengis.net/ont/geosparql) which also supports representations of polygons with WKT. In the GND GeoSPARQL is already used but as far as I can see they also do not indicate the reference model, see e.g. these examples: http://d-nb.info/gnd/4007328-2/about/lds & http://d-nb.info/gnd/4074335-4/about/lds.

Before completely switching to GeoSPARQL we might also indicate the reference model adding this to the context: `"Point": "http://www.w3.org/2003/01/geo/wgs84_pos#Point"` and the type information to the data:

```json
{
  "@id" : "http://lobid.org/resource/HT015579730",
  "dct:spatial" : {
    "type": "Location",
    "id": "http://www.wikidata.org/entity/Q365",
    "geo": {
      "type": [ "GeoCoordinates", "Point" ],
      "lat": 50.942222222222,
      "lon": 6.9577777777778
    },
    "label": "Köln"  
    }
}
```

The description of `http://www.w3.org/2003/01/geo/wgs84_pos#Point` isn't unambiguous, though: 
> A point, typically described using a coordinate system relative to Earth, such as WGS84

`http://www.w3.org/2003/01/geo/wgs84_pos#lat` and `http://www.w3.org/2003/01/geo/wgs84_pos#long` are unambiguous, though:

> The WGS84 latitude of a SpatialThing (decimal degrees).
> The WGS84 longitude of a SpatialThing (decimal degrees).

We could also use those instead of the schema.org stuff.

**Comment by acka47** [comment]
+1 We can deploy this on production and do the improvements of the wikidata matching later. I will open a separate issue re. indicating the geo reference system.
