### ISSUE TITLE
ALMA-Fix: How to deal with Confrences?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1366]
The Alma Morph had a `conference`-element that does not exist in lobid.
How should we deal with `conferences`?

**Comment by TobiasNx** [comment]
This should be fixed with #1424 too

**Comment by acka47** [comment]
This is assigned to me but the issue misses information for me to add to the discussion:

- About which MARC21 field(s) are we talking? – I guess it is 111.
- How does an MARC21 example snippet look like?
- What is the relation to #1353?

If we are talking about MARC field 11, we should take orientation from Bibframe and pull it into the `contribution` array. See the file `[Fields 1XX, 7XX, 8XX – Names](https://www.loc.gov/bibframe/mtbf/ConvSpec-1XX,7XX,8XX-Names-v1.7.xlsx)` at https://www.loc.gov/bibframe/mtbf/ where it reads about `111`: 

> See Process 0-names/titles and Process 1-names

In [Process notes](https://www.loc.gov/bibframe/mtbf/ConvSpec-Process0-8-v2.0.docx) it reads about names/titles conversion:

```
<resource>	bf:contribution     [	a 	bf:Contribution ;
	bf:agent     [	a	bf: Person, Organization, Meeting, Family or Jurisdiction  
				rdfs:label			“label from Process 1.3”;
				identifiedBy   [	a 	Identifier  …..	   ];	see Subfield $0 spec
				bflc:nameXXMatchKey     	“string from Process 1.1”;
				bflc:nameXXMarcKey		“string from Process 1.2” ] ;
		bf:role	  [    a	bf:Role		
		[rdfs:label    	“…”  ];				see Process 1.4	
				bf:code	“…”      ] ].			see Process 1.4
		If URI from ID for role, then instead:
		bf:role		URI for role
```

> If name is from 1XX: 
> Use bflc:PrimaryContribution instead of bf:Contribution

Does this answer your questions, @TobiasNx ?

**Comment by TobiasNx** [comment]
should have been more specific:

is the result okay:
https://github.com/hbz/lobid-resources/pull/1424/commits/43542fb811d967e7e5101b109743c9a2b04ae5c1

**Comment by acka47** [comment]
Adding example MARC21 snippets for context:

https://github.com/hbz/lobid-resources/blob/d8af6b7f2c4434c4cc69565737c109ffa182b0cd/src/test/resources/alma-fix/990011470300206441.xml#L71-L80

https://github.com/hbz/lobid-resources/blob/d8af6b7f2c4434c4cc69565737c109ffa182b0cd/src/test/resources/alma-fix/990065341720206441.xml#L50-L60

https://github.com/hbz/lobid-resources/blob/d8af6b7f2c4434c4cc69565737c109ffa182b0cd/src/test/resources/alma-fix/99371107766906441.xml#L132-L134

I think, the result must be improved. The authority entries in the first two examples are about about one specific instance of a conference but we only take the name of the conference _series_. I am not sure what is the best solution from these options:

1. We could add information to the `label` field, e.g. "International Ichthyology Congress (7 : 1991 : Den Haag)" instead of "International Ichthyology Congress".
2. We could do 1.) plus adding some additional fields for rendition (subfield `n`), year (subfield `d`) and plase (subfield `c`). 

I propose to start with one as we don't know whether the additional subfields would be of any use for anyone.

**Comment by acka47** [comment]
See also this related old ticket about conference labels: https://github.com/hbz/lobid-resources/issues/696

**Comment by TobiasNx** [comment]
Closed with: https://github.com/hbz/lobid-resources/commit/555a24900e6191cb982ec92f3ecc28d5b253ef73
