### ISSUE TITLE
ALMA-FIX: Links and relation metadata

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1390]
- [ ] `sameAs`
- [x] `fulltextOnline[]`
- [ ] `hasVersion[]`
- [x] `similar[]`
- [x] `bibliographicCitation`
- [x] `containedIn[]`
- [x] `supplement[]`
- [x] `description[]`
- [x] `primaryForm[]`
- [x] `seeAlso[]`

These need to be added to the transformation.
These are quiet difficult to reconstruct from the old morph and many are buidling from the same Aleph elements `655`, `59?`, and `52?`

**Comment by TobiasNx** [comment]
@acka47 primaryForm transformation in ALEPH MORPH say it links to primary and secondary form and vice versa. Isn't this contradicting the relation primaryForm and only true for the http://purl.org/dc/terms/isFormatOf which is the URI behind `primaryForm`.

https://github.com/hbz/lobid-resources/blob/69d0c8b011f83905e0114fc0a79069c86ab1e084/src/main/resources/morph-hbz01-to-lobid.xml#L1469-L1474

In ALMA I only used the link of the secondary to the primary, not the other way around. okay?

**Comment by TobiasNx** [comment]
What is the difference between `sameAs` and `similar`?

**Comment by dr0i** [comment]
From https://github.com/hbz/lobid-resources/issues/1475#issuecomment-1302141011: 
> Re ''seeAlso": I also can't find any examples, though I also couldn't make a comprehensive query. Just checked the 4 test files which formerly had that data, matched by:
```xml
 <data source="655[-eu][ -1].[x3]">
 <regexp match="^[zZ][uU][sS]"/>
</data>
```
> Seems to be gone from the catalog. I assume we can get rid of `seeAlso`

Depends on https://github.com/hbz/lobid-resources/issues/1509.

**Comment by dr0i** [comment]
By configuring [index-config.json](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/index-config.json) to index `seeAlso` I got a bunch of errors when ETLing the basedump, e.g.:
 > [1412]: index [resources-alma-fix-20221108-1045], type [resource], id [990219911120206441], message [MapperParsingException[failed to parse [seeAlso]]; nested: IllegalStateException[Can't get text on a START_OBJECT at 1:1711];]


So:
1. we have examples now (because of the error logs)
2. we don't want them to be _searchable_, but it should be in the document source. It _is_ ,see  [990219911120206441](http://test.lobid.org/resources/search?q=990219911120206441&format=json)

So: we just don't configure `seeAlso` to the searchable index (aka `index-config.json] but leave it as ist is.  Everything is alright with the `seeAlso`. @TobiasNx can you take this example into the test files?

**Comment by dr0i** [comment]
Added `seeAlso` in [e1f85](https://github.com/hbz/lobid-resources/commit/f6e1f85860078c5d4bc3a454876f8113af329019) .

**Comment by TobiasNx** [comment]
These elements have all been added. To document the differences see #1400
