### ISSUE TITLE
ALMA-Fix: Redirect for hbzId-lobid-URL to ALMAMMSId-lobid-URL

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1433]
With ALMA hbzId also known as "HT-Nummern" are discontinued for new catalog entries. Old entries keep them but new ones will not have any. They only have the ALMA-MMS-Ids. These will be the new leading ids for the entries.

To keep the old URIs of lobid-ressources we need a redirect from the hbzId-lobid-URL to the ALMAMMSId-lobid-URL.

This still needs refinement since it is not clear where the redirect will be set.

**Comment by dr0i** [comment]
This works already, see e.g. https://test.nwbib.de/HT020968842.
But you cannot use the almammsId, e.g. https://test.nwbib.de/99370849894106441.
Question is, if _both_ cases should work.

**Comment by fsteeg** [comment]
Does not work yet for https://test.lobid.org/resources/HT020968842, see also https://github.com/hbz/lobid-resources/issues/1342.

**Comment by dr0i** [comment]
Not sure if https://github.com/hbz/lobid-resources/issues/1330 should be resolved to be able to solve this here.

**Comment by fsteeg** [comment]
Deployed to test: https://test.lobid.org/resources/HT020968842

This is how it works: if the direct ID access yields no result (because for Alma, the index ID is the almaMmsId, not the hbzId), we run a search for the hbzId and redirect (301, moved permanently), see https://github.com/hbz/lobid-resources/commit/06104c3f66730c041f47160ee1d9034fe4feed2e. Some possible options: we could change how to redirect (e.g. 303, 'see other') or we could directly serve the record, without redirect (e.g. we'd stay at `https://test.lobid.org/resources/HT020968842`). @acka47, you also mentioned that we might want to add the old URLs to the data (that would happen on the transformation level, right?). Assigning you for functional review.

**Comment by acka47** [comment]
+1 I think a 301 redirect is the best solution.

> you also mentioned that we might want to add the old URLs to the data (that would happen on the transformation level, right?)

Yes, I think, we should add a [`dnb:deprecatedUri`](https://d-nb.info/standards/elementset/dnb#deprecatedUri) statement to each resource that indicates the old URI e.g. for the example resource (in N-Triples): `<http://lobid.org/resources/99370849894106441#!> <https://d-nb.info/standards/elementset/dnb#deprecatedUri> "https://test.lobid.org/resources/HT020968842#!" .` This probably calls for a separate issue, doesn't it?

**Comment by TobiasNx** [comment]
Should we add `deprecatedUri` to all ressources that have HT-Numbers? In my opinion It would be difficult to differentiate between records prior and after the switch to ALMA-Fix.

**Comment by fsteeg** [comment]
> This probably calls for a separate issue, doesn't it?

Yes. Leaving myself assigned here for deployment after PR #1522 is reviewed by @dr0i.
