### ISSUE TITLE
Remodel `bibliographicCitation`?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1444]
https://github.com/hbz/lobid-resources/blob/2ae7b86259115ee3fa8693e3ba16ebda2739ca54/src/main/resources/alma/fix/otherFields.fix#L111-L131

Should we remodel `bibliographicCitation`? so it fits the broader concept? Or only keep it for articles?

**Comment by acka47** [comment]
This is important for NWBib and RPB and changing it would mean an API break and some adjustments to the UI. Furthermore, we are following the DINI AG KIM ["Empfehlung für die RDF-Repräsentation bibliografischer Daten"](https://wiki.dnb.de/pages/viewpage.action?pageId=68060017) here, see https://wiki.dnb.de/display/DINIAGKIM/MARC+21-RDF-Mapping. Closing.

**Comment by acka47** [comment]
(I understand your discomfort with this solution, though.)

**Comment by TobiasNx** [comment]
Then we should only keep it for articles right? Since we have no type article at the moment. I do need to reopen it and filter it.

**Comment by TobiasNx** [comment]
@acka47 Should only articles have `bibliographicCitation`?
In ALEPH I found this: http://lobid.org/resources/HT018627673#! is this wrong?

**Comment by acka47** [comment]
> Should only articles have bibliographicCitation or all records that have containedIn?
In ALEPH I found this: http://lobid.org/resources/HT018627673#! is this wrong?

This looks like a very special case and we should probably keep the `bibliographicCitation` as also the type `Book` could be incorrect. We won't know without further investigation but it probably only affects a tiny part of the data so that this has very low priority.

**Comment by TobiasNx** [comment]
Closing for now.
