### ISSUE TITLE
Can Manuscripts also be Prints?

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1450]
https://github.com/hbz/lobid-resources/blob/ac8c976fa7f19b32adc2261d9623b0dc3a3190c7/src/main/resources/alma/fix/mediumAndType.fix#L217-L224

**Comment by TobiasNx** [comment]
What about reproductions of manuscripts?

**Comment by acka47** [comment]
> What about reproductions of manuscripts?

If they can be identified, they should probably have medium "Print". Generally, I am happy to leave these decisions about scarcely recorded mediums like manuscript or microform to you. Please just document them clearly in the issue so that we in the future can easily find the rationale behind the transformation.

**Comment by TobiasNx** [comment]
Only 25 resources now have both:

http://lobid.org/resources/search?medium=http%3A%2F%2Frdaregistry.info%2FtermList%2FRDAproductionMethod%2F1010%2Chttp%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FManuscript%2CAND&from=15

I think that we can close this ticket for now.
