### ISSUE TITLE
ALMA-Fix: Add `corporateBodyForTitle`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1482]
Seems to be based on. https://github.com/hbz/lobid-resources/issues/33

Mapping ALEPH -> ALMA is:

333# $a [nur RAK] | 245 10 $a ... / < 333# $a > | Zu ergänzende Urheber zum Haupttitel [nur RAK]Hz: Neu
-- | -- | --

https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=483000321

**Comment by TobiasNx** [comment]
It seems that the info is old RAK metadata. See [HT007015768](https://lobid.org/resources/HT007015768):

```
 "corporateBodyForTitle": [
    "Kommission der Europäischen Gemeinschaften, Zentraldienst Archiv, Dokumentation, Abteilung IX/C/3"
  ],
```

=

```
          <datafield tag="331" ind1="-" ind2="1">
            <subfield code="a">Dokumentationsbulletin</subfield>
          </datafield>
          <datafield tag="333" ind1="-" ind2="1">
            <subfield code="a">Kommission der Europäischen Gemeinschaften, Zentraldienst Archiv, Dokumentation, Abteilung IX/C/3</subfield>
          </datafield>
```

In [ALMA](https://alma.lobid.org/marcxml/990055713370206441):

```
<datafield tag="245" ind1="1" ind2="0">
    <subfield code="a">Dokumentationsbulletin / Kommission der Europ&#228;ischen Gemeinschaften, Zentraldienst Archiv, Dokumentation, Abteilung IX/C/3</subfield>
    <subfield code="b"> = Bulletin de renseignement documentaire / Commission des Communaut&#233;s Europ&#233;ennes, Service Central Archives-Documentation (SCAD), Division IX/C/3 = Bollettino di informazione documentaria / Commissione delle Comunit&#224; Europee, Servizio Centrale Archivi-Documentazione, Divisone IX/C/3</subfield>
    <subfield code="n">[...]</subfield>
    <subfield code="p">A</subfield>
    <subfield code="n">[...]</subfield>
    <subfield code="p">Sondernummer</subfield>
  </datafield>
```

@acka47 should we drop `corporateBodyForTitle` then?

**Comment by acka47** [comment]
As there is no MARC21 equivalent to `333` (see below), we won't need `corporateBodyForTitle` any more.

To be totally clear, do I understand correctly: In RAK the title got split up into `331` and `333` and we separated them in the JSON (`title` and `corporateBodyForTitle`) and had to concatenate both fields for display purposes. In MARC21, there is only `245` where this is already concatenated. We thus copy `245` into `title` and display it, so that users won't see a difference. Right?

This means, that we will be able to delete this UI code related to `corporateBodyForTitle` when we switch to an Alma-based index:

https://github.com/hbz/lobid-resources/blob/352d5f628046f05eb7b191202163bcd29dc13708/web/app/views/details.scala.html#L27

https://github.com/hbz/lobid-resources/blob/352d5f628046f05eb7b191202163bcd29dc13708/web/app/views/tags/result_doc.scala.html#L177

**Comment by TobiasNx** [comment]
> To be totally clear, do I understand correctly: In RAK the title got split up into `331` and `333` and we separated them in the JSON (`title` and `corporateBodyForTitle`) and had to concatenate both fields for display purposes. In MARC21, there is only `245` where this is already concatenated. We thus copy `245` into `title` and display it, so that users won't see a difference. Right?

Correct. hbz ALMA-MARC concetinates both elements in 245 $a
