### ISSUE TITLE
ALMA-Fix: Detailpage provides no link for Zum Bestand siehe:/containedIn

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1592]
http://test.lobid.org/resources/990223412180206441#!

![grafik](https://user-images.githubusercontent.com/61879957/211795488-872a87b4-4176-4da7-96b5-6d7aed3c9c1f.png)

also not in in:
![grafik](https://user-images.githubusercontent.com/61879957/211796050-d5244cc7-5a2a-42c9-b958-31c2f191aeb0.png)

Compare the old:
http://lobid.org/resources/HT019620889#!

**Comment by fsteeg** [comment]
The problem here is that Alma-Lobid, which uses almaMmsIds like 990223412180206441, is referencing the containedIn resource with the hbzId, HT019620889. What happens is that the system takes the hbzId, and tries to get a label for the resource (from itself), which failes, since it would need the almaMmsId here.

We could change the logic to make it work (here, we could take the label directly from the data, or we could do a search instead of a simple get-by-id request). However, I'd assume that these links should be updated to almaMmsIds anyway, right? Because after going productive with Alma-Lobid, a link like `http://lobid.org/resources/HT005062736#!` (the value of containedIn in current Alma-Lobid)  wouldn't work anymore.

**Comment by TobiasNx** [comment]
I am not sure if the internal linking in the Verbundskatalog will be updated, so that the "old" hbzIds will be exchanged for ALMA MMS Ids. If they are not updated we only create links with the old hbzId.

@blackwinter  : Do you know if the linked resource IDs will be updated or enriched by the ALMA MMS Ids?

e.g.:
```
<datafield tag="773" ind1="0" ind2="8">
<subfield code="i">Enthalten in</subfield>
<subfield code="t">Städte- und Gemeinderat</subfield>
<subfield code="d">Düsseldorf, März 2018</subfield>
<subfield code="g">72. Jahrgang, 03 (März 2018), Seite 10-12</subfield>
<subfield code="w">(DE-605)HT005062736</subfield>
</datafield>
```
Will subfield `$w` be changed to 990054471200206441 or receive an additional element?

**Comment by acka47** [comment]
> I was wrong here, we actually already redirect these: http://test.lobid.org/resources/HT005062736

So we just have to update the code to follow the redirect when fetching the label?

**Comment by blackwinter** [comment]
> Do you know if the linked resource IDs will be updated or enriched by the ALMA MMS Ids?

No, AFAIK they won't.

**Comment by fsteeg** [comment]
Fixed by getting the label based on the same logic as the redirect.

Deployed to test: https://test.lobid.org/resources/990223412180206441

**Comment by fsteeg** [comment]
Reassigning to @acka47 for functional review since Tobias is on leave.

**Comment by acka47** [comment]
+1 Closing
