### ISSUE TITLE
ALMA-Fix: Use former title 247 as `alternativeTitle`

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-resources#1599]
Should we use former title as alternativeTitle?

**Comment by acka47** [comment]
Example: https://test.lobid.org/resources/990054147370206441

MARC:

```xml
<datafield tag="245" ind1="0" ind2="0">
  <subfield code="a">Familiendynamik</subfield>
  <subfield code="b">systemische Praxis und Forschung</subfield>
</datafield>
<datafield tag="247" ind1="0" ind2="0">
<subfield code="a">
interdisziplinäre Zeitschrift für systemorientierte Praxis und Forschung
</subfield>
<subfield code="f">Zusatz bis 2008</subfield>
</datafield>
```

Note, tthat there is this an annotation in subfield f.

In the current lobid it apparently is added to `alternativeTitle`, see https://lobid.org/resources/HT002191991#!. Thus, I think we should do it with the Alma-based data as well so that people can find a journal based on the old name.

**Comment by dr0i** [comment]
Should be deployed at Monday.

**Comment by dr0i** [comment]
Checked - works.
Closing.
