### ISSUE TITLE
Unify ZDB and RPB id fields and URLs

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#1727]
With the latest changes regarding ZDB-IDs (see #1709), we should probably unify:

- RPB-IDs in field `rpbId`, e.g. `RPB929t114497` with URL `http://rpb.lobid.org/RPB929t114497`
- ZDB-IDs in field `zdbId`, e.g. `123550-3` with URL `https://lobid.org/resources/ZDB-123550-3`

So probably: change `rpbId` to e.g. `929t114497` and URL to e.g. `http://rpb.lobid.org/RPB-929t114497`

**Comment by TobiasNx** [comment]
The ZDB ID is 123550-3. We "only" use for the links between resources https://lobid.org/resources/ZDB-123550-3 since all ZDB titles lost or will lose their HT number. And we want to keep the users within the zdb cosmos.

`zdbId` is only the number 23550-3

The links should be refered under `sameAs`

http://ld.zdb-services.de/resource/507495-2
http://rpb.lobid.org/RPB929t114497
http://nwbib.lobid.org/HT020573547

**Comment by fsteeg** [comment]
Hm, yes, not sure what you mean. In case I was not clear, my suggestion is changing the `rpbId` handling to bring it in line with the `zdbId`:

> change `rpbId` to e.g. `929t114497` and URL to e.g. `http://rpb.lobid.org/RPB-929t114497`

i.e. change the content of the `rpbId` field to use the plain, non-prefixed ID, and prefix `RPB-` for the URLs, both as it now works for the `zdbId`.

**Comment by TobiasNx** [comment]
ah, alright +1

**Comment by TobiasNx** [comment]
https://github.com/hbz/lobid-resources/pull/1728 

I made a suggestion. 
I also added links to `sameAs`.

**Comment by dr0i** [comment]
Re https://github.com/hbz/lobid-resources/commit/a8424b10b4702deb59cbd1e73107eb2f113a6759 : you merged this into master, but didn't deploy it. Are you going to deploy?

**Comment by TobiasNx** [comment]
I am not able to deploy ;-) can you do this :)

**Comment by dr0i** [comment]
Deployed. Closing.
