### ISSUE TITLE
Transformation problems with marcel:aui and marcrel:ant

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#190]
The different role markers in the source `[Vorl.]` and `[Vorw.]` – as well as similar spellings – aren't always mapped to the right role. See e.g. HT016556189. In [API 1.0](http://lobid.org/resource/HT016556189/about) there are two relations made out of `[Vorl.]`: the – correct –   marcrel:ant and the incorrect marcrel:aui. 

```json
"http://id.loc.gov/vocabulary/relators/ant" : {
      "@id" : "http://d-nb.info/gnd/11851928X"
    },
    "introductionBy" : "http://d-nb.info/gnd/11851928X",
```

In [API 2.0](http://lobid.org/resources/HT016556189), however, we only have the incorrect relation:

```json
{
   "contribution":{
      "agent":{
         "id":"http://d-nb.info/gnd/11851928X",
         "label":"Carroll, Lewis",
         "type":[
            "Person"
         ]
      },
      "role":{
         "id":"http://id.loc.gov/vocabulary/relators/aui",
         "label":"Einleitung"
      },
      "type":[
         "Contribution"
      ]
   }
}
```

See [lines 1317-1319](https://github.com/hbz/lobid-resources/blob/536fd9ce6d4795b8ad6613b0c48814f5c3e3188e/src/main/resources/morph-hbz01-to-lobid.xml#L1317-L1319) and [1335-1337](https://github.com/hbz/lobid-resources/blob/536fd9ce6d4795b8ad6613b0c48814f5c3e3188e/src/main/resources/morph-hbz01-to-lobid.xml#L1335-L1337) of the current morph.

**Comment by ChristophEwertowski** [comment]
Caroll has now the role relators/ant. See [example (production)](http://lobid.org/resources/HT016556189) / [example (test)](http://test.lobid.org/resources/HT016556189). 
Also the examples are corrected which are labeled as "Bibliographic antecedent" because the related MAB fields contain the string ```ant```, like ```Gesamtver*ant*wortung```. See [example (production)](http://lobid.org/resources/HT016791198) / [example (test)](http://test.lobid.org/resources/HT016791198).
Now only strings like ```[ant]``` or ```ant``` are matched but not strings which contain the three letter string. The same is done for all other english abbrevations of the roles.

**Comment by acka47** [comment]
+1
