### ISSUE TITLE
wrong currentLibrary

### ISSUE THREAD

**Issue by hagbeck** [hbz/lobid-resources#1962]
Hi,
in recent months, we have relocated numerous holdings to new buildings. We have also made these changes in Alma. In lobid-resources, almost all the changes have also been implemented. However, we are also aware of at least 70 data records that still have the old, no longer valid value for currentLibrary.
Example: http://lobid.org/resources/990227795740206441.json - Here ZB is still in currentLibrary.
Where does this come from?

**Comment by acka47** [comment]
Thanks for letting us know, @hagbeck . Unfortunately, I have little experience with this and @TobiasNx is on parental leave. We will see what we can do.

**Comment by blackwinter** [comment]
Apparently, the record hasn't been published since 2023-09-09. The change is present in Alma, but hasn't triggered a publishing of the associated record.

We are currently in the process of switching to a new full publishing (due to similar issues reported by IntrOX libraries). In this publishing the current library for your example is `SM`. But Ex Libris support is having difficulties enabling the improved publishing algorithm for the new profile, and the default algorithm is too slow for timely updates. So we can't switch until this situation has been rectified.

Even then it's unclear whether future updates will be published correctly. Can you give us more details, so we can open a case with Ex Libris support? (A list of examples along with modification dates and expected vs. actual metadata.)

**Comment by blackwinter** [comment]
Also, counterexamples from the same time frame would be helpful as well.

**Comment by hagbeck** [comment]
We have tried to find more information. We were dealing with the process with the ID 8849728220006445: "Physische Exemplar-Informationen ändern - ZB::Freihand - 30/10/2023 17:39:33". 
315,883 item records were changed. These are all items in the current location SM/Magazin. A process report was not generated by Alma (instead it says: "The report was not generated due to the number of records required to be calculated"...
But there are also incorrect ones from other processes.
An example of a correct item / correct title: http://lobid.org/resources/990029052320206441.json

**Comment by blackwinter** [comment]
I don't know if this is enough to go on, but I'll open a support case.

Which e-mail address(es) should I add to receive notifications?

**Comment by blackwinter** [comment]
I've created Ex Libris support case 07021802.

**Comment by blackwinter** [comment]
We've switched to the new full publishing last weekend, so your example is correct now. If you find more discrepancies, please let us know.
