### ISSUE TITLE
Duplicate ZDB records in lobid-resources

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#2088]
Reported by RPB editor @DorisCollin [in RPB-214](https://jira.hbz-nrw.de/browse/RPB-214):

> In diesem Zusammenhang fällt mir auf, das Zeitschriftentitelaufnahmen dublett in lobid-ressouces sind:
>
> https://lobid.org/resources/990054196250206441
>
> https://lobid.org/resources/991000579049708980
>
> Beide haben die ZDB-ID  "zdbId" : "1091-1", die Alma-Titelaufnahme des 2. Titels existiert aber nicht mehr in Alma

**Comment by dr0i** [comment]
In such a case we have to wait until the deletions are also reflected in lobid-resources, i.e. after the weekend. 
(Unfortunately we don't seem to have a possibility to check in Alma _when_ something was removed from the database.)
If the resource then _still_ exists we have to talk with upstream people to find the source of the problem.

**Comment by TobiasNx** [comment]
I think we have another problem with the lookup i think. The second record is an IZ record: 991000579049708980. I don't know how @DorisCollin found this. You can identify this with regard to the last four digits: 8980.

**Comment by TobiasNx** [comment]
This record still seems to exist in the IZ of Karlsruhe: https://hbz-hkl.primo.exlibrisgroup.com/discovery/fulldisplay?context=L&vid=49HBZ_HKL:VU1&search_scope=MyInst_and_CI&tab=Everything&docid=alma991000579049708980

It is neither a dubplicate record nor a deleted record.

Within lobid there exist the NZ(which was the Verbundkatalog), some electronical portfolios coming from the CZ (due to workflows of e-book-resource-management) and also records from some IZ if granted access.

This can lead to multiple hits for one zdbId: e.g. her example: https://lobid.org/resources/search?q=zdbId%3A1091-1 leads to 3 records.

 if @DorisCollin only wants to filter the NZ for their ZDB records she should the inCollection statement for the NZ too:
https://lobid.org/resources/search?q=zdbId%3A1091-1+AND+inCollection.id%3A%22http%3A%2F%2Flobid.org%2Forganisations%2FDE-655%23%21%22%2C (Only one hit.)

**Comment by acka47** [comment]
> if @DorisCollin only wants to filter the NZ for their ZDB records she should the inCollection statement for the NZ too:

@fsteeg We should probably add the `inCollection` filter to all the lobid union catalogue lookups, shouldn't we?

**Comment by fsteeg** [comment]
Sounds good, I'll open an issue in RPB to add NZ filters (http://lobid.org/organisations/DE-655).

And this here can be closed, right?

**Comment by TobiasNx** [comment]
In my opinion yes!
