### ISSUE TITLE
Replace isPartOf with inSeries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#231]
I think we can adjust the [morph, lines 1613-L1624](https://github.com/hbz/lobid-resources/blob/28100eff6e40f0847084c28c719ebabb3aa811bd/src/main/resources/morph-hbz01-to-lobid.xml#L1613-L1624) by using the `inSeries` construct instead of `isPartOf`. This would make the data more homogenous.,

**Comment by ChristophEwertowski** [comment]
That wouldn't contain articles in monographies, compilations and *Lieferungswerke* (ongoing works?). [This article](http://lobid.org/resources/TT002609390) is part of a monography. We could change ```inSeries``` to ```isPartOf``` which is a part of our favorite vocabulary but also broader than the first property. So I would stick to isPartOf because it has a different meaning.

**Comment by ChristophEwertowski** [comment]
What do you mean to the above comment @acka47 ?

**Comment by ChristophEwertowski** [comment]
@acka47 I think the last status of our offline discussion was to leave it as it is. Because of that I'm closing this issue. If I misinterpreted and didn't convince you, simply reopen the ticket.
