### ISSUE TITLE
Add datatypes to startDate, endDate

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#297]
i.e. add to the `@context`. (I presume we normalize all dates in the transformation.)

```json
"startDate": {
  "@id": "http://schema.org/startDate",
  "@container": "@set",
  "@type": "http://www.w3.org/2001/XMLSchema#gYear"
},
"endDate": {
  "@id": "http://schema.org/endDate",
  "@container": "@set",
  "@type": "http://www.w3.org/2001/XMLSchema#gYear"
}
```

Related to #285.

**Comment by ChristophEwertowski** [comment]
@acka47 Then also shouldn't dateOfBirth and dateOfDeath be of the same type? And dateCreated of the type "http://www.w3.org/2001/XMLSchema#date" and all identifiers of the type "http://id.loc.gov/ontologies/bibframe/Identifier"?

**Comment by ChristophEwertowski** [comment]
Also adds the same datatype to dateOfBirth and dateOfDeath. Because XML Schema gYear allows only four digit numbers year statements with only three digits are expanded by a leading 0. As an example for this change see [HT014215912 (production)](http://lobid.org/resources/HT014215912?format=json) and [HT014215912 (test)](http://test.lobid.org/resources/HT014215912?format=json).

**Comment by acka47** [comment]
+1
