### ISSUE TITLE
Transform all relator types

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#3]
Currently, there are some relator types we haven't covered in the RDF. See for example http://lobid.org/resource/HT016161271.

[Source](http://lobid.org/resource?id=HT016161271&format=source) (snippet):

``` xml
<datafield tag="100" ind1="e" ind2="1">
  <subfield code="p">LÃ¶hr, Frank</subfield>
  <subfield code="d">1971-</subfield>
  <subfield code="b">[Ltg.]</subfield>
  <subfield code="9">(DE-588)135213304</subfield>
</datafield>
<datafield tag="104" ind1="e" ind2="1">
  <subfield code="p">Berning, Thomas</subfield>
  <subfield code="d">1966-</subfield>
  <subfield code="b">[Ltg.]</subfield>
  <subfield code="9">(DE-588)135101042</subfield>
</datafield>
<datafield tag="108" ind1="e" ind2="1">
  <subfield code="p">Krahforst, Gereon</subfield>
  <subfield code="d">1973-</subfield>
  <subfield code="b">[Org]</subfield>
  <subfield code="9">(DE-588)13779830X</subfield>
</datafield>
```

**Comment by acka47** [comment]
This one has low priority, just submitting it to keep it in mind.

**Comment by acka47** [comment]
In the example, we would chose http://id.loc.gov/vocabulary/relators/led for `[Ltg.]` ("Leitung") and http://id.loc.gov/vocabulary/relators/mus for `[Org]` ("organist") as there is no specific relator code for organist.

**Comment by acka47** [comment]
Another one is `[Sopran]`. Example: http://lobid.org/resource/HT014525099

[Source](http://lobid.org/resource?id=HT014525099&format=source) (snippet):

```xml
<datafield tag="104" ind1="e" ind2="1">
  <subfield code="p">AugÃ©r, Arleen</subfield>
  <subfield code="d">1939-1993</subfield>
  <subfield code="b">[Sopran]</subfield>
  <subfield code="9">(DE-588)129389641</subfield>
</datafield>
```

Should be mapped to relator code http://id.loc.gov/vocabulary/relators/sng ("singer") as a specific "soprano" relator doesn't exist.

**Comment by acka47** [comment]
See also https://github.com/lobid/lodmill/issues/759 which deals with transforming relator types from RDA records to RDF.

**Comment by ChristophEwertowski** [comment]
Transformed the relator types which were located in the subfield "b". In the following csv are the types which I transformed, to which role and if I added the role or not. 
[Transform relator types.txt](https://github.com/hbz/lobid-resources/files/847137/Transform.relator.types.txt) 
I didn't transform "Bearb." because the only role which I could think of which would fit, would be contributor and that's our default. For "Textverf." I found out that of 8 hits five were in the context of an opera, one for theatre and I think two for normal articles. Don't know if we can transform this role to *[Writer of added lyrics](http://id.loc.gov/vocabulary/relators/wal.html)* on this basis. The rest like "Angebl. Verf." I didn't include because of probably too few affected resources.

**Comment by ChristophEwertowski** [comment]
Here is a list of example resources which should be changed. I will assign this issue, if the tests ran through and I got the test instance up to the new status.

resource | relator
--- | ---
http://lobid.org/resources/HT014525099 / http://test.lobid.org/resources/HT014525099 | Alt -> singer, Sopran -> singer, Tenor -> singer
(Maybe existent in staging system?) | Bariton, Bass -> singer
http://lobid.org/resources/HT015429967 / http://test.lobid.org/resources/HT015429967 | Begr. -> originator
http://lobid.org/resources/HT006266886 / http://test.lobid.org/resources/HT006266886 | Darst. -> actor
http://lobid.org/resources/HT017608824 / http://test.lobid.org/resources/HT017608824 | Dir. -> conductor
http://lobid.org/resources/HT019093814 / http://test.lobid.org/resources/HT019093814 | Fotogr. -> photograph
http://lobid.org/resources/TT000075751 / http://test.lobid.org/resources/TT000075751 | Gesang -> singer, Gitarre -> instrumentalist, Harfe -> instrumentalist, Klavier -> instrumentalist 
http://lobid.org/resources/HT008357204 / http://test.lobid.org/resources/HT008357204  | Hrsg. -> editor
http://lobid.org/resources/HT007845782 / http://test.lobid.org/resources/HT007845782 | Ill. -> illustrator
http://lobid.org/resources/TT003060292 / http://test.lobid.org/resources/TT003060292 | Komp. -> componist, Libretto -> librettist
http://lobid.org/resources/HT008357263 / http://test.lobid.org/resources/HT008357263 | Komponist -> componist
http://lobid.org/resources/HT016161271 / http://test.lobid.org/resources/HT016161271 | Ltg. -> leader
http://lobid.org/resources/HT008357329 / http://test.lobid.org/resources/HT008357329 | Red. -> redakteur
http://lobid.org/resources/HT015090208 / http://test.lobid.org/resources/HT015090208 | Regie -> director
http://lobid.org/resources/HT008357194 / http://test.lobid.org/resources/HT008357194 | Regisseur -> director
http://lobid.org/resources/TT003060418 / http://test.lobid.org/resources/TT003060418 | Sopr -> singer
http://lobid.org/resources/CT003012479 / http://test.lobid.org/resources/CT003012479 | Sprecher -> speaker
http://lobid.org/resources/TT003060292 / http://test.lobid.org/resources/TT003060292 | Ten -> singer
http://lobid.org/resources/CT002004665 / http://test.lobid.org/resources/CT002004665 | Widmungsempfänger -> dedicatee

**Comment by ChristophEwertowski** [comment]
@acka47 : Ready to review. See list above. There is no example for the agent with the speaker role because it is located in the field 800 (http://lobid.org/hbz01/CT003012479).
Two questions remain from point of view: 
* Should we take the 800s into account? I wouldn't do it.
* Should we take all 100s for agents? Not only those in "Ansetzungsform" but also pseudonyms, earlier and later names?

**Comment by acka47** [comment]
Looks good, except for some labels:

- "Librettist" -> "Libretto"
- "Begründer" -> "Begründer/in"
- "Interpret" -> "Interpret/in"
- "Instrumentalist" -> "Musiker/in"

Furthermore:
- Add `[Org]` role in source to http://id.loc.gov/vocabulary/relators/itr (example: http://test.lobid.org/resources/HT016161271)


Also, http://test.lobid.org/resources/HT016161271 seems to have the problem mentioned in #206 .

**Comment by ChristophEwertowski** [comment]
Test index is built. Example for the role ```Interpret/in```: http://test.lobid.org/resources/HT017608824. As discussed offline with @acka47 , the 800s are not used for roles anymore and the 100s are decreased to every fourth field of the Ansetzungsform (excluding corporations the agents work for, identification numbers for the agents (GND-id is included in the Ansetzungsform), and pseudonyms, earlier/later names). Because of that the code could be reduced.

**Comment by acka47** [comment]
+1
