### ISSUE TITLE
Add contributor facet

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#306]
Contributors can not be filtered after a search. Before implementing this, we have to decide two things:

1. Which roles should be taken into account in the facet? (All roles, only creator, something in between?)
2. Should the facet include corporate bodies or just persons?

**Comment by fsteeg** [comment]
To keep this simple on the implementation side (and realistically add this for the launch), I suggest we build it just like the advanced search, to include all contributing agents (all roles, persons, corporations).

**Comment by ChristophEwertowski** [comment]
1. Not all roles should be used for the facet. Agents with a role like "Basiert auf das Werk von" (if I think about it, I will correct the label in the next commit) don't do something really important for the work. My suggestions are: 

Roles which I would include | Roles which I wouldn't include
--- | ---
Creator, actor, screenwriter, componist, cinematographer (camera), cartograph, musician, photograph, performer, singer, publisher, issuing body and maybe engraver, illustrator, interviewer and interviewed person. | Introduction/Afterword, Bibliographic antecedent, collaborator, conductor, collector, contributor, director, dedicatee, honoured person, producer, redacteur.

Otherwise, implement them all. If the one facet isn't enough, a second one will do the trick. And if for example a person searched for a director and earlier actor, if would be unlogical from the user perspective to only get the resources where the faceted person was an actor (Live thinking on GitHub! ;) ) 
2. I would include them. I just looked at the first 30 resources which have a corporateBody as an agent. In all cases they are the only agent for the resource. So even if they have the role contributor they are important for the work.

**Comment by fsteeg** [comment]
Deployed to staging: http://stage.lobid.org/resources/search?q=ehrenfeld

**Comment by acka47** [comment]
I like very much (+1) and suggest to move the facet one up (after the "Erscheinungsjahr" facet and before the "Schlagwörter" facet).

Obviously, a new facet enables one to find more flaws in the application. Reviewing this, I noticed that http://stage.lobid.org/resources/search?q=generative+grammatik gives 42508 results, including 4073 by Homer (not Simpson) where I don't find neither of the search terms. But this is something for another issue...

**Comment by ChristophEwertowski** [comment]
+1 Also for moving the facet one position upwards.

**Comment by fsteeg** [comment]
> I noticed that http://stage.lobid.org/resources/search?q=generative+grammatik gives 42508 results, including 4073 by Homer (not Simpson) where I don't find neither of the search terms.

"Homerus, Grammatiker": http://lobid.org/resources/HT009028375?format=json
