### ISSUE TITLE
Implement scroll parameter

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#330]
Subissue of https://github.com/hbz/lobid/issues/288

**Comment by fsteeg** [comment]
Updated title, since there is no scroll parameter implemented in lobid-resources 2.0 yet.

Some links provides by @dr0i in mail correspondence with @hagbeck:

- https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html
- http://elasticsearch-users.115913.n3.nabble.com/Is-ES-capable-of-doing-pagination-td3399087.html
- https://github.com/hbz/lobid/issues/176

**Comment by fsteeg** [comment]
For consistency, we should implement this for lobid-organisations too.

**Comment by fsteeg** [comment]
Current implementation deployed to production:
http://lobid.org/resources/search?q=ehrenfeld&format=bulk

We will do the actual functional review for this as part of https://github.com/hbz/lobid/issues/329

For details on the implementation see https://github.com/hbz/lobid-resources/pull/372#issue-219932827
