### ISSUE TITLE
Wrong display of top-level description field

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#339]
~~Details view still uses `description` field for table of contents, resulting in wrong details:
http://lobid.org/resources/CT003071915~~

~~Actual field: [http://lobid.org/resources/search?q=tableOfContents.id%3A*](http://lobid.org/resources/search?q=tableOfContents.id%3A*)~~

See https://github.com/hbz/lobid-resources/issues/339#issuecomment-309730784 below for actual issue.

**Comment by fsteeg** [comment]
We should also display the `publication.description` content in a correct way, as brought up by @acka47 in https://github.com/hbz/lobid-resources/issues/361#issuecomment-291070862.

**Comment by fsteeg** [comment]
In the current code, we display two fields: `description` as "Inhaltsangabe" and `tableOfContents` as "Inhaltsverzeichnis". The (top-level) `description` field seems to be gone: [http://lobid.org/resources/search?q=description%3A*](http://lobid.org/resources/search?q=description%3A*) (still present in the context though). The `publication.description` is a different thing. I seem to recall that the old `description` linked to abstracts.

@acka47 @ChristophEwertowski @dr0i: was that field renamed? Is it gone on purpose?

**Comment by ChristophEwertowski** [comment]
The top-level descriptions contained links if 655[-eu][ -1].[x3] was "Inhaltstext" (found it at an old local branch). Now they are put at `publication.description`.

**Comment by acka47** [comment]
> The (top-level) `description` field seems to be gone: 

The top-level description field still exists, you just used the wrong query. Try http://lobid.org/resources/search?q=description.id%3A*.

**Comment by acka47** [comment]
We might use `publication.note` instead of `publication.description`. We already use `publication.note` with information from field `523 ANGABEN UEBER ERSCHEINUNGSWEISE UND ERSCHEINUNGSDAUER`. I am quite sure that this always gets into the `PublicationEvent` object while the current `publication.description` comes from `610 FUSSNOTE ZUR SEKUNDAERAUSGABE`  and thus is always associated with the `SecondaryPublicationEvent` object. Thus, these wouldn't interfere, respectively we don't have to concatenate if both are found in one record. However, having different information in `publication.note` (depending on the publication event type) might also be a problem if we want to show it in the UI...

**Comment by fsteeg** [comment]
Deployed to staging:

http://stage.lobid.org/resources/CT003071915 (no description, no toc, contains wrong link in production)
http://stage.lobid.org/resources/HT019007247 (description and toc, using the included labels for links)

**Comment by acka47** [comment]
Looks good. +1 At some point we should show the "Inhaltsangabe" text in lobid instead of just linking to the DNB page...
