### ISSUE TITLE
Remove isPartOf statements that are redundant to inSeries/volumeIn

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#382]
I became aware of this by a mail from @hagbeck. We introduced `inSeries` and `volumeIn` already in API 1.0 (https://github.com/lobid/lodmill/issues/497) to associate a isPartOf relation with the right volume numbering. Back then we retained the older and then redundant `isPartOf` information and wanted to remove it in API 2.0. Although we removed the `volume` information (see https://github.com/hbz/lobid-resources/issues/8#issuecomment-273430034), the redundant `isPartOf` data still exists.

`inSeries` example [HT016132962](http://lobid.org/resources/HT016132962?format=json):

```json
{
   "id":"http://lobid.org/resources/HT016132962#!",
   "inSeries":[
      {
         "numbering":"1",
         "series":[
            {
               "id":"http://lobid.org/resources/HT016132955#!",
               "label":"lobid Ressource"
            }
         ],
         "type":[
            "SeriesRelation"
         ]
      }
   ],
   "isPartOf":[
      {
         "id":"http://lobid.org/resources/HT016132955#!",
         "label":"lobid Ressource"
      }
   ]
}
```

`volumeIn` example [HT019268984](http://lobid.org/resources/HT019268984?format=json):

```json
{
   "id":"http://lobid.org/resources/HT019268984#!",
   "isPartOf":[
      {
         "id":"http://lobid.org/resources/HT019268980#!",
         "label":"lobid Ressource"
      },
      {
         "id":"http://lobid.org/resources/HT015736981#!",
         "label":"lobid Ressource"
      }
   ],
   "volumeIn":[
      {
         "multiVolumeWork":[
            {
               "id":"http://lobid.org/resources/HT019268980#!",
               "label":"lobid Ressource"
            }
         ],
         "numbering":"1",
         "type":[
            "MultiVolumeWorkRelation"
         ]
      }
   ]
}
```

Note that the volume even has the link to the series as ispPartOf which should only be (and already is, see http://lobid.org/resources/HT019268980?format=json) linked from the superordinated resource with `inSeries`.

**Comment by acka47** [comment]
http://lobid.org/resources/HT002888677?format=json from the old issue is a good example as it contains both `inSeries` and `volumeIn` relationships.

**Comment by ChristophEwertowski** [comment]
Commenting out / removing the lines 1790-97 seems to do the trick. It also removes statements which are additionally in ```containedIn```. The problem is that there are some zdb-URLs which aren't resolved and not found elsewhere in the file ([example](http://lobid.org/resources/HT003654516?format=json)). Relies on https://github.com/hbz/lobid-resources/issues/386.

**Comment by ChristophEwertowski** [comment]
Superflous ```isPartOf```-links removed. See [example for inSeries (production)](http://lobid.org/resources/HT016132962?format=json) /  [example (test)](http://test.lobid.org/resources/HT016132962?format=json) and [example for inVolume (production)](http://lobid.org/resources/HT019268984?format=json) / [example (test)](http://test.lobid.org/resources/HT019268984?format=json). 
Some ```isPartOf```-links aren't covered anymore because they come from secondary sources (ind2="2", see second example). 
As discussed today ZDB-links are also removed because we have equivalent lobid resources. See [example (production)](http://lobid.org/resources/HT003654516?format=json) / [example (test)](http://test.lobid.org/resources/HT003654516?format=json).

**Comment by acka47** [comment]
+1
