### ISSUE TITLE
Show complete DDC

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#400]
Only the first class is shown but not the subClasses, see http://lobid.org/resources/HT019301219?format=json. The reason is a wrong regular expression.

[Source](http://lobid.org/hbz01/HT019301219) (snippet):

```xml
<datafield tag="700" ind1="b" ind2="1">
   <subfield code="a">914.3</subfield>
</datafield>
```

Current JSON-LD: 

```json
{
   "subject":[
      {
         "id":"http://dewey.info/class/914/",
         "label":"Geografie Europas und Reisen in Europa",
         "source":{
            "id":"http://d-nb.info/gnd/4149423-4",
            "label":"Dewey-Dezimalklassifikation"
         }
      }
   ]
}
```
Also dewey.info seems to be down. I only get an error 500 (internal server error).

**Comment by dr0i** [comment]
Yes , OCLC '#rules#sucks#g'.
Just short before OCLC took down dewey.info I grapped the data (see http://lobid.org/download/dumps/other/) which is openly licensed (i.e. *not* the subclasses unfortunatley (if I remebered correctly @acka47 ?).

**Comment by ChristophEwertowski** [comment]
I had a notion that there was a catalog which lists the DDC notation and a link to the label of it but apparently I was wrong. The BVB lists keywords and notations but not which notations belong to which keywords ([example](http://gateway-bayern.de/BV040127636)).

**Comment by ChristophEwertowski** [comment]
From our discussion multiple possible ways of handling this emerged:
1. leave it as it is
2. only show the notation, remove not resolving URL
3. if notation and label exist, show both; if not, show only notation from MAB ```700.b```. Remove not resolving URL

I prefer the last option. If we have the information we shouldn't loose it.

**Comment by acka47** [comment]
+1 for option 3.)

**Comment by aquast** [comment]
I'm not sure at all, but isn't there a german "version" of ddc provided by DNB that uses all openly licensed notations (pre-decimal position) but also some post decimal positions I will see if I can find some info about

**Comment by acka47** [comment]
You probably mean http://deweysearchde.pansoft.de/webdeweysearch/. I don't know whether it is of much use. We might scrape the data to get the labels. But I don't think we should link to it (e.g. using URLs like http://deweysearchde.pansoft.de/webdeweysearch/executeSearch.html?query=121).

**Comment by aquast** [comment]
ehem yes, skip my idea, it's not helpful 👎

**Comment by nichtich** [comment]
German DDC Translation (and some other languages) are licensed under CC-BY-NC-ND. See <https://github.com/scriptotek/mc2skos> for a tool to convert DDC from its original format to SKOS. @danmichaelo has full DDC data in Norwegian (see http://data.ub.uio.no/skosmos/ddc/en/ for LOD), VZG has full DDC data in German but I cannot tell how to share this data because of the f******* license.

**Comment by danmichaelo** [comment]
Are you sure you're not allowed to share numbers and headings @nichtich ? My interpretation of the CC-BY-NC-ND license has been that it should be OK to share the same data that is publicly available at WebDeweySearch in another format (SKOS), as format conversion and (non-creative) aggregation should be acceptable under -ND. But I'm not sure if the license tag is supposed to be read literally.. 

(There's also the German WebDeweySearch API that could be used instead of scraping, but I think only one class can be requested at a time: http://webdeweysearchde.pansoft.de/webdeweysearch/rest?query=004 )

**Comment by dr0i** [comment]
The `NC` (Non-Commercial) is incompatible with any open license.

> For example, in 2014 the non-profit German public broadcaster Deutschlandradio was successfully sued for using an NC photo on its website, as the court interpreted NC as 'purely private use'." (http://community.oscedays.org/t/why-are-non-commercial-licenses-not-open-source/569). 

Also, there is the "infringing when incorporating" problem (ibidem).

**Comment by acka47** [comment]
Thanks for the pointer to the WebDeweySearch API, @danmichaelo. I wasn't aware of this.

For our use cases, a URI for a DDC notation currently is not necessary. Thus, we should have in mind the actual issue: We want to have the complete DDC in our data and not only the first three levels. For the [example resource](http://lobid.org/resources/HT019301219) this means that we want the notation `914.3` plus the German label ("Geografie Deutschlands und Reisen in Deutschland" or so) in the data, like so (mapping `notation` to `http://www.w3.org/2004/02/skos/core#notation` in the `@context`):

```json
{
   "subject":[
      {
         "notation": "914.3",
         "label":"Geografie Deutschlands und Reisen in Deutschland",
         "source":{
            "id":"http://d-nb.info/gnd/4149423-4",
            "label":"Dewey-Dezimalklassifikation"
         }
      }
   ]
}
```

For this we need the complete DDC and the German labels. As far as I know we have a file with the 22nd edition and German labels somewhere. Furthermore, we can get the information via the German WebDeweySearch API. I suggest to proceed as follows:

- Add lower levels as well as labels and notations for all levels to [dewey.json](https://github.com/hbz/lobid-resources/blob/master/src/main/resources/labels/dewey.json) file. (We can either get the data from the WebDewey API or from the DDC file we already have.)
- Make it possible to add labels in the process of creating JSON-LD based on notation instead of uri. (@jschnasse, @dr0i: Can this be done with little effort?)

**Comment by acka47** [comment]
We should revisit this one soon.

**Comment by acka47** [comment]
Oups, we have forgotten to revisit this before the official launch. Now we have dewey.info URIs in the data which don't resolve (and will not anytime soon as the service has died). What to do?

**Comment by acka47** [comment]
We will have to reopen #470 when this is implemented.

**Comment by ChristophEwertowski** [comment]
`notation` and `source` are added within the [branch 400](https://github.com/hbz/lobid-resources/tree/400-showDDC). The field `label` is missing because of the missing `id`s. @dr0i: How difficult is it to get labels if a notation is there instead of an URL-id? Should we first implement the other fields of the Raumsystematik?

**Comment by aquast** [comment]
Is this issue solved for edoweb also? What do we have to do? Thanks, A.

**Comment by dr0i** [comment]
>  How difficult is it to get labels if a notation is there instead of an URL-id?

In principle: not  very hard. You would to it another way, though.You would need a lookup table of some sort in the morph. If the data is small (say <100MB), which is the case for DDC, it's easiest to make a `csv` like for e.g. `sigel-isil` lookup.

**Comment by dr0i** [comment]
@aquast This issue here is not solved yet. I wouldn't know of an issue you have in edoweb with DDC, but _if_ you would like to see full DDC notation _with_ a label on it incoorparoated in our API 2.0 of lobid-resources: you will have exactly that!
Thanks for the remonder of this issue, anyway. I gave an answer to @ChristophEwertowski so that he can further work on this issue when he is back from vacation next week.

**Comment by dr0i** [comment]
Thx @danmichaelo, wrote this script to get a csv with all 40k ddc's with their German label. Lines look like e.g.: `354.47|Kernbrennstoffe`
```
#!/bin/bash
# get all ddc's with their german label as csv
IFS="
"

lookup() {
deweys=$(printf "$1|" ; curl "http://webdeweysearchde.pansoft.de/webdeweysearch/rest?query=$1" | xmlstarlet sel -t -v "/webdeweySearchResult/ddcResult/caption" -n  -t -v "webdeweySearchResult/ddcResult/child")
if [ -n "$deweys" ]; then
	for i in $deweys; do
		sleep 0.05 # be kind - throttle down
		echo "$i" | grep -q '|'
		if [ $? = "0" ]; then
			echo $i >> deweys.csv
		else
			lookup $i
		fi
	done
fi
}

i=0
while [ $i -lt 9 ]; do
	i=$(expr $i + 1 )
	lookup $i
done

```

**Comment by ChristophEwertowski** [comment]
Added labels, see "Landflächen..." at [TT050427581 (production)](http://lobid.org/resources/TT050427581.json) / [TT050427581 (test)](http://test.lobid.org/resources/TT050427581.json) for MAB `705`. For MAB `700b` see [HT019248596 (production)](http://lobid.org/resources/HT019248596.json) [HT019248596 (test)](http://test.lobid.org/resources/HT019248596.json). 

As you can see in the pull request multiple resources seem to loose DDC subjects. Short story: The contents don't seem to be DDC notations in all cases.
I removed the contents from MAB 700 with indicator "-" / blank. In the short description of the MAB fields it is written that the contents should be of "Systematik der katalogisierenden Institution". Additional to the subfield with the MAB number 700- also have a second subfield a with `DNB` or `ZDB` in it. So I asked a collegue from the Verbundgruppe about if these contents are DDC or an own notation. She wasn't sure. I told her about "06" in a MAB 700- field of [HT013304490](http://lobid.org/hbz01/HT013304490) which according to her is an old notation of the DNB. A second example is [HT018782520](http://lobid.org/hbz01/HT018782520) which contains a "K" at MAB 700-.

Got an E-Mail from Mrs. Blanckenhagen about the used system of the DNB for subjects (called „DNB-Sachgruppe“). Mostly they use the DDC directly but sometimes they only orientate themselves on the DDC (http://www.dnb.de/DE/Service/DigitaleDienste/DNBBibliografie/gliederungDnb.html).

**Comment by ChristophEwertowski** [comment]
Note: I have to think about how to handle the missing labels file that Travis doesn't throw errors.

**Comment by acka47** [comment]
It looks like the labels are generated by concatenating the label of the superordinated notation plus the subordinate notation, see e.g "914.3" in http://test.lobid.org/resources/HT019248596.json: 

```json
{
    "label" : "Geografie Mitteleuropas und Reisen in Mitteleuropa    Geografie Deutschlands und Reisen in Deutschland",
    "notation" : "914.3",
    "source" : {
      "id" : "http://d-nb.info/gnd/4149423-4",
      "label" : "Dewey-Dezimalklassifikation"
    }
  }
```

@dr0i and me had discussed this at some point and I recall we decided to only add the label for the concrete (i.e. subordinate) notation. In this case, this would be "Geografie Deutschlands und Reisen in Deutschland".

Re. omitting the notations with indicator blank, I think we should continue using the "DNB" notations. The variations from DDC seem to be minimal and we obviosuly already exclude notations on production that can not be from DDC like "06" in http://lobid.org/hbz01/HT013304490.

**Comment by ChristophEwertowski** [comment]
It is correct, see [link at WebDewey Search](http://deweysearchde.pansoft.de/webdeweysearch/executeSearch.html?lastScheduleRecord=913-919&lastTableRecord=&query=914&catalogs=DNB&_catalogs=on&catalogs=GBV&_catalogs=on&catalogs=HeBIS&_catalogs=on&catalogs=SUB&_catalogs=on&catalogs=SWB&_catalogs=on&catalogs=FUB&_catalogs=on) (hopefully it works). `914` is "Geografie Europas und Reisen in Europa" and `914.3` is "Geografie Mitteleuropas und Reisen in Mitteleuropa    Geografie Deutschlands und Reisen in Deutschland" (don't know why there is space as a dividing sign). 
As for the other notations: OK.

**Comment by acka47** [comment]
+1 then for the labels. Re. "DNB" notations, are they relevant for the customer who requested this? Otherwise we might also include them at a later point.

**Comment by ChristophEwertowski** [comment]
Too late. Added them again yesterday and I'm not removing them again as long as nobody complains. I'm assigning the pull request for functional review.

**Comment by ChristophEwertowski** [comment]
In addition to the "Vollständige Notation" from subfield a I also added "Grundnotation" from subfield c which according [to the DNB wiki] is the same as the notation in the printed edition of the DDC. See HT015455455 in the [pull request](https://github.com/hbz/lobid-resources/pull/581/files). The complete notation (subfield a) has no label. I'm going to add it to the test index tomorrow.
