### ISSUE TITLE
Two contradictory 'edition' values

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#415]
See http://lobid.org/resources/HT018957942

Reported by @hagbeck via mail.

When discussed offline, we said `edition` should never have multiple values.

**Comment by ChristophEwertowski** [comment]
At the moment we take MAB fields 400, 403 and 510 for ```edition```, see `<data source="40[03]-1.[an]" name="$[ns-bibo]edition"/>` and `<data source="510-1.a" name="$[ns-bibo]edition"/>`. We should take MAB 400 ("Ausgabebezeichnung in normierter Form") first and if it doesn't exist 403 ("Ausgabebezeichnung in Vorlageform") and then 510 ("Angaben zur Ausgabebezeichnung"). In this case it would lead us to the wrong "11" because it is wrongly cataloged (both DNB catalog and publisher only refer to the "1. Auflage"). The issue with the wrong cataloging is dealt with in #258.

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [example](https://test.lobid.org/resources/HT018781534).

**Comment by acka47** [comment]
+1
