### ISSUE TITLE
No Aleph XML source for some resources

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#436]
Submitted by Dominik S., RWTH via phone and email.

> http://lobid.org/hbz01/HT019313225
> funktioniert nicht.
> 
> Seltsam ist, dass das hier etwas liefert:
> http://lobid.org/resource?id=HT019313225
> aber wenn man dort auf Source geht, kommt derselbe Fehler wie oben.
> 
> Ich habe hier noch eine Liste mit weiteren HT-Nummern, die Probleme machen; Eure Standardbeispiele funktionieren dagegen.

**Comment by acka47** [comment]
Here are some more problematic entries:

> HT019309356
HT019312261
HT019309829
HT019311161
HT019315361
HT019320665
HT019316948
HT019313225
HT019311659
HT019312343
HT019312173
HT019319851
HT019313438
HT019319871

**Comment by dr0i** [comment]
Seems like the data is, unlike the other data (lobid-resources etc) only updated daily. Problem is, when one day was falling and that wasn't manually repeated, it won't heal itself (by weekly full reindexing).
There must be once a basedump indexed but I can't find that. Do you know how what to do @fsteeg ?

**Comment by dr0i** [comment]
Btw, logs seemd fine for me. No error seen.

**Comment by fsteeg** [comment]
Currently indexing baseline-2017051306 and updates into hbz01-20170517-110000 on gaia-aither.

**Comment by fsteeg** [comment]
Deployed to production:

http://lobid.org/hbz01/HT019313225
http://lobid.org/hbz01/HT019309356
http://lobid.org/hbz01/HT019312261
http://lobid.org/hbz01/HT019309829
http://lobid.org/hbz01/HT019311161
http://lobid.org/hbz01/HT019315361
http://lobid.org/hbz01/HT019320665
http://lobid.org/hbz01/HT019316948
http://lobid.org/hbz01/HT019313225
http://lobid.org/hbz01/HT019311659
http://lobid.org/hbz01/HT019312343
http://lobid.org/hbz01/HT019312173
http://lobid.org/hbz01/HT019319851
http://lobid.org/hbz01/HT019313438
http://lobid.org/hbz01/HT019319871

**Comment by acka47** [comment]
+1 Thanks. Closing.

**Comment by fsteeg** [comment]
Brought up offline by @dr0i: we should add weekly full indexing to avoid this issue in the future.

**Comment by dr0i** [comment]
Also scheduled this in crontab.
Btw revisioned `root@weywot1:/var/spool/cron/crontabs` using the `git@gaia.`
To be checked again next week.

**Comment by dr0i** [comment]
Deployed to production.

**Comment by dr0i** [comment]
Fails because of non-determined suffix of the basedump file. Above Pull Request takes care of this.

**Comment by schmitzd** [comment]
Still we have a resource that does not work:
[HT019331383](http://lobid.org/hbz01/HT019331383)

**Comment by fsteeg** [comment]
@dr0i: You reopened this a day ago, after closing the latest pull request, was that on purpose? Were you aware of any issue? @acka47 has unassigned you today, I'll reassign you for now.

To the actual issue reported by @schmitzd. I tried switching to the new index (hbz01-20170421-110000), which was not aliased yet, and added all updates we have for that baseline. No success, plus many other resources (from above) were missing. I then tried replaying the latest updates on the older index, but HT019331383 is still missing. I'll trigger a new index creation for the baseline plus updates (and delete the non-aliased, faulty hbz01-20170421-110000 index).

**Comment by fsteeg** [comment]
I confused the old index with a new one, what I thought was a new one was actually from last month. So it all makes some more sense now: @dr0i had probably reopened because the automatic baseline indexing failed (as he described above) and we're not using the latest baseline right now.

Triggered full indexing: `sol@quaoar1:~/git/mabxml-elasticsearch$ nohup curl --fail -XPOST "http://localhost:7300/hbz01/transform?dir=/home/sol/git/mabxml-elasticsearch/updates/&suffix=gz&cluster=gaia-aither&hostname=193.30.112.82&index=hbz01-20170524-170000" >> logs/processMabxml.sh.20170524-manual-gaia.log 2>&1 &`

Deployment note to self: if this fixes the issue, index additional updates before switching the alias.

**Comment by fsteeg** [comment]
Deployed to production: http://lobid.org/hbz01/HT019331383

This was fixed by using the new baseline index. As for the underlying issue, I'm not aware of any catalog data issues in recent days (as the one that caused the original missing items). Assigning @dr0i for review and possible additional analysis.

**Comment by dr0i** [comment]
> @dr0i: You reopened this a day ago, after closing the latest pull request, was that on purpose?

Yes. Because I wanted to review if the automatic workflow goes well.

I think the issue results from the intervention of the daily updates:
since the basedump indexing needs more than 24h and the daily updates share the temporary directory of the to be indexed files the basedump-file got wiped by the daily update routine.
Opened a new Pull Request to use a separate directory for basedump file.

**Comment by dr0i** [comment]
Logs indicate success this time. Closing.
