### ISSUE TITLE
Don't set type "EditedVolume" when "Series" is given

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#460]
There are currently 875 resources that are of type `Series` and `EditedVolume`, example: http://lobid.org/resources/HT001232755#!

This doesn't make sense, we should only set type `EditedVolume` in these cases. 

(This issue has low priority.)

**Comment by ChristophEwertowski** [comment]
Deployed to test. See [HT003651380 (production)](http://lobid.org/resources/HT003651380?format=json) / [HT003651380 (test)](http://test.lobid.org/resources/HT003651380?format=json) which is only an `EditedVolume` because a `Series` doesn't contain ISBNs. [HT013056453 (production)](http://lobid.org/resources/HT013056453?format=json) / [HT013056453 (test)](http://lobid.org/resources/HT013056453?format=json) is a `Series` because an `EditedVolume` doesn't contain a frequency. [HT017894012 (production)](http://test.lobid.org/resources/HT017894012?format=json) / [HT017894012 (test)](http://test.lobid.org/resources/HT017894012?format=json) is a `Series` because a `EditedVolume` doesn't have an ISSN. There are 37 resources left which don't have any of this criteria and therefore stay both `Series` and `EditedVolume`.

**Comment by acka47** [comment]
Hmm, the ISBN criterium unfortunately doesn't work for http://lobid.org/resources/HT003651380. It obviously is a series as it has volumes but it also has an ISBN. It si probably best to add to the list of cataloging errors and deploy this. +1

**Comment by ChristophEwertowski** [comment]
Done.
