### ISSUE TITLE
MapperParseingException: hasVersion

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#502]
Presumably since https://github.com/hbz/lobid-resources/commit/01d0da29d530d1f3bc1fe220cefbd5535b244afe we got a lot (i.e. 1565) of `MapperParsingException`, resulting in a drop of these docs, see e.g. http://lobid.org/resources/HT009371770 (vs. old index: http://stage.lobid.org/resources/HT009371770.json where the `hasVersion` was not exitsing at all).

The logs shows e.g. this:

> ...   ],
   "hasVersion" : [
      "purl?PPN632092866",
      {
         "id" : "http://resolver.sub.uni-goettingen.de/purl?PPN632092866",
         "label" : "http://resolver.sub.uni-goettingen.de/purl?PPN632092866"
      }
   ],
   "describedBy" : {
...
>  /var/log/elasticsearch/gaia-aither.log.2017-07-02:MapperParsingException[object mapping for [hasVersion] tried to parse field [null] as object, but found a concrete value]

which seems to be a broken data structure.

**Comment by ChristophEwertowski** [comment]
Yes, the commit is the reason for the missing resources. I added the example resource to the branch  [502-mapperParserExceptionHasVersion](https://github.com/hbz/lobid-resources/tree/502-mapperParserExceptionHasVersion). If the new `hasVersion` is commented out, the input and json files are generated. If not, the files are dropped. 

Also the copied part of the log doesn't originate from the example resource HT009371770. There it is simply:
`
"hasVersion":["2027/njp.32101058716331"],
"hbzId":" ...
`
The copied log belongs to HT006590585 ([MAB-XML](http://lobid.org/hbz01/HT006590585)).

**Comment by ChristophEwertowski** [comment]
Now 552b is added to `hasVersion` if it contains an URL-link which doesn't contain an URN or DOI ([example HT006590585 (production)](http://lobid.org/resources/HT006590585) / [example (test)](http://test.lobid.org/resources/HT006590585)). Also expanded the definition of the DOI to `552[ab][-1].a` because of the many DOIs which aren't in MAB `552a` ([example HT018774908 (hbz01)](http://lobid.org/hbz01/HT018774908) / [example (test)](http://test.lobid.org/resources/HT018774908?format=json)). Furthermore URNs which start with `nbn:de` are added to the URN field with the prefix `urn:` in front of it (if there is no 655 which contains it). The  ([HT018138676 (hbz01), field 552b](http://lobid.org/hbz01/HT018138676) / [json (test), see URN field](http://test.lobid.org/resources/HT018138676?format=json)).

**Comment by acka47** [comment]
+1 Looks good to me, I haven't tired to understand all the details, though...
