### ISSUE TITLE
Create automatic notification if a resource is dropped

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#518]
If we have added the current removed resources we will need an automatic notification if a resource is dropped. For example let the script which greps the error messages of the dropped resources run daily and if there are results, send them per mail to semweb.

**Comment by dr0i** [comment]
We have a script now which checks if the updates of the MabXmlClobs are correctly indexed. We don't have that for the fulldump, though, because that is too much data. So , for the fulldump we still may want to have that script of notifiation of dropped resources (note that there still can be silently dropped resources).
As the updates are checked I don't think this is so important, though.
Postponed.

**Comment by dr0i** [comment]
Done. Commited into our internal git repo:
git@gaia:/files/open_data/closed/gitServer/checkLobid.git
Closing.
