### ISSUE TITLE
Add possibility to filter subject / contribution search by type

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#532]
As mentioned in https://github.com/hbz/nwbib/issues/163#issuecomment-315118385. 

**"Autoren- und Körperschaftssuche"**

We need to be able to query `contribution.agent.label{searchterm}+OR+contribution.agent.altLabel:{searchterm}` and filter the results by type `Person` or `CorporateBody`.

**Sachbegriff/Person/Ort-als-Schlagwort-Suche**

I just realized that we actually can't implement this in an optimal way before https://github.com/hbz/lobid-resources/issues/116#issuecomment-270688708 is done. As soon as we have an `altLabel` field for single subjects, we will be able to query `subject.componentList.label:{searchterm}+OR+subject.componentList.altLabel:{searchterm}` and filter the results by type `SubjectHeading`, `Person` or `PlaceOrGeographicName`.

If #116 isn't implemented soon enough, there are two possible workarounds:
1. query only `subject.componentList.label:{searchterm}` and filter by type (false negatives will be missing from results because alt labels are not queried)
2. query `subject.componentList.label:{searchterm}+OR+subjectAltLabel_{searchterm}` and loom whether the expected type is somewhere in `componentList` (results will have false positives)

However, this ticket is about generally filter label/altLabel queries by resource type.

**Comment by fsteeg** [comment]
To allow these kind of searches, the `contribution` and `subject` fields need to get the `nested` datatype, see https://www.elastic.co/guide/en/elasticsearch/reference/5.6/nested.html

This is required for NWBib Körperschaftssuche based on API 2, see https://github.com/hbz/nwbib/issues/163, and might help with NWBib Themensuche too, see https://github.com/hbz/lobid-resources/issues/639.

**Comment by fsteeg** [comment]
Deployed to stage:

### In `subject.componentList`

Normal search:
http://stage.lobid.org/resources/search?q=subject.componentList.label%3AFreudenberg+AND+subject.componentList.type%3ASubjectHeading

Nested search:
http://stage.lobid.org/resources/search?nested=subject.componentList&q=subject.componentList.label%3AFreudenberg+AND+subject.componentList.type%3ASubjectHeading

### In `subject`

Normal search:
http://stage.lobid.org/resources/search?q=subject.label%3AWestfalen+AND+subject.source.label%3ASachsystematik

Nested search:
http://stage.lobid.org/resources/search?nested=subject&q=subject.label%3AWestfalen+AND+subject.source.label%3ASachsystematik

### In `contribution`

Normal search:
http://stage.lobid.org/resources/search?q=contribution.agent.label%3ASCHOLLE+AND+contribution.role.label%3AAutor

Nested search:
http://stage.lobid.org/resources/search?nested=contribution&q=contribution.agent.label%3ASCHOLLE+AND+contribution.role.label%3AAutor

**Comment by acka47** [comment]
Hmm, I am not sure that this is always working as intended. See e.g. http://stage.lobid.org/resources/search?q=subject.componentList.label%3AFreudenberg+AND+subject.componentList.type%3APerson where I find two entries that do not have a subject that has as label something with "Freudenberg" and as type "Person": [Wenn Elvis im Treppenhaus rockt](http://stage.lobid.org/resources/BT000148168) [Jürgen Sawahn - Ehrenbürger von Mór](http://stage.lobid.org/resources/BT000134991).

**Comment by acka47** [comment]
Works like a charm, also my favourite example of all books that have Harry Rowohlt as translator, using IDs instead of labels: http://stage.lobid.org/resources/search?q=contribution.agent.id%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%2F107828553%22+AND+contribution.role.id%3A%22http%3A%2F%2Fid.loc.gov%2Fvocabulary%2Frelators%2Ftrl%22

What I notice that always thecontribution and subjectfacets don't load and for the last "contribution" query also the other facets take really long to load. :-/

**Comment by fsteeg** [comment]
There was some dependency issue on the server breaking the contribution and subject facets.

After an `sbt clean` and a restart these now work again.

**Comment by fsteeg** [comment]
Added `nested` sample to API documentation: http://stage.lobid.org/resources/api#query-syntax

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
As mentioned offline yesterday:

I had to change the nested param syntax to include the actual query string, so that we can combine nested queries and normal queries. Here are the examples from above with the new syntax 
`nested=<nested field>:<query string>`:

### In `subject.componentList`

Normal search:
http://stage.lobid.org/resources/search?q=subject.componentList.label%3AFreudenberg+AND+subject.componentList.type%3ASubjectHeading

Nested search:
http://stage.lobid.org/resources/search?nested=subject.componentList:subject.componentList.label%3AFreudenberg+AND+subject.componentList.type%3ASubjectHeading

### In `subject`

Normal search:
http://stage.lobid.org/resources/search?q=subject.label%3AWestfalen+AND+subject.source.label%3ASachsystematik

Nested search:
http://stage.lobid.org/resources/search?nested=subject:subject.label%3AWestfalen+AND+subject.source.label%3ASachsystematik

### In `contribution`

Normal search:
http://stage.lobid.org/resources/search?q=contribution.agent.label%3ASCHOLLE+AND+contribution.role.label%3AAutor

Nested search:
http://stage.lobid.org/resources/search?nested=contribution:contribution.agent.label%3ASCHOLLE+AND+contribution.role.label%3AAutor

I also updated the API documentation: http://stage.lobid.org/resources/api#query-syntax
