### ISSUE TITLE
Fix automatic updates

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#541]
Since server migration on 2017-07-27 our automatic update process is broken.

The Aleph updates are not appearing in their expected location, see:
http://lobid.org/download/dumps/DE-605/mabxml/

I've manually created and indexed updates for the missing period, see https://github.com/hbz/lobid-resources/issues/537.

See `hduser@weywot1$ crontab -e` for all steps involved.

The issues seem to be caused by missing or inaccessible locations for the update files.

For `weywot1:/home/hduser/git/hbz-aleph-dumping/bin` I had to `sudo` `bash -x daily-hbz-aleph.sh`

I have now changed the access rights and it worked manually as `hduser`, will run via cron tonight.

I've copied the file created from Aleph via `scp` to provide it to the indexing in hbz01, API 1, and API 2.

For `weywot1:/home/hduser/git/lodmill/lodmill-rd/doc/scripts/hbz01` (API 1) and `gaia:/opt/hadoop/git/lobid-resources` (API 2) indexing I had to `export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` before `bash -x startHbz01ToLobidResources.sh [...]`.

I'll continue to manually index the updates until the automatic updates are restored.

**Comment by fsteeg** [comment]
Should also update https://github.com/hbz/lobid-resources#data-updates for Aleph data, URL, paths.

**Comment by fsteeg** [comment]
Automatic creation of the Aleph update via cron worked, publishing did not, indexed manually.

**Comment by fsteeg** [comment]
Created local directory `/files/open_data/open/DE-605/mabxml/` on weywot1, which makes the file available to the API 1 transformation (via `toBeUpdateFilesXmlClobs_afterBasedump.txt`), and tweaked `weywot1:/home/hduser/git/hbz-aleph-dumping/bin/daily-hbz-aleph.sh` to additionally publish via `scp` to quaoar1, which makes the update file available to the API 2 transformation on gaia, and to the web server via http://lobid.org/download/dumps/DE-605/mabxml/, which is used by the mabxml-elasticsearch indexing on quaoar1.

**Comment by fsteeg** [comment]
Same tweak for `weywot1:/home/hduser/git/hbz-aleph-dumping/bin/fulldump-hbz-aleph.sh`.

Next automatic updates will run via cron tonight, next baseline on the weekend.

**Comment by fsteeg** [comment]
Automatic updates ran fine tonight. Keeping issue open for baseline processing on the weekend.

**Comment by fsteeg** [comment]
Baseline processing worked, subsequent updates look good too, closing. Retaining 1 old index as backup.

**Comment by dr0i** [comment]
Underlying problem was a NFS problem: the NFS couldn't be mounted because un `/etc/fstab` resided not only the good location but also another location which doesn't exist anymore. Trying to mount that bad location results in an error and skips the mounting of the good location.

- removed the bad location.
- mounted with `# mount -a`
- reverted your changes

Now it should be guaranteed again that not more than 7 files are exported.

Review tomorrow.

**Comment by dr0i** [comment]
This will also resolve a mayor issue concerning the indexing of fulldumps:
Because of the missing mount the script couldn't update the location of the newest fulldump (`aliasNewestFulldump.tar.gz`) which is used by both, lobid-resource and lobid-resources, as noted in https://github.com/hbz/lobid-resources#production:

> The base-file must be referenced by a symbolic link residing in the nfs: “/files/open_data/closed/hbzvk/index.hbz-nrw.de/alephxml/clobs/baseline/aliasNewestFulldump.tar.gz”. It is this symbolic link which is used by indexing processes.

The API1.0 worked because the index wasn't switched thus only used an old (but daily updated) index.

Thus:
I switched the index for API2.0 back to the old fulldump base , just to be sure.

Todo:
check next monday if the script (getting the fulldump out of aleph; publish correctly AND update the alias for the internal index workflow) runs OK again.

**Comment by dr0i** [comment]
Acknowledge working daily updates.

**Comment by dr0i** [comment]
Acknowledge working weekly updates. Closing.
