### ISSUE TITLE
Add living statistics which don't consist of year specifications

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#552]
For example in [HT017260117](http://lobid.org/hbz01/HT017260117) MAB `902-1.d` or [HT018924091](http://lobid.org/hbz01/HT018924091) in `100-1.d`. Maybe adding it as `note`.

**Comment by ChristophEwertowski** [comment]
An edoweb customer wants the living statistics behind the keyword.

**Comment by acka47** [comment]
>  I propose to simply add it behind the existing label.

What about using the `gndo:dateOfBirthAndDeath` like the GND does, see e.g. http://d-nb.info/gnd/1093886471/about/lds?

**Comment by ChristophEwertowski** [comment]
Deployed the changes to test. See "Apollinaris" in [TT002001274 (production)](http://lobid.org/resources/TT002001274.json) / [TT002001274 (test)](http://test.lobid.org/resources/TT002001274.json). Also added a commit which wasn't pushed and adds `dateOfBirth` and `dateOfDeath` if BC. See "Pindaros" in [HT007847893 (production)](http://lobid.org/resources/HT007847893.json) / [HT007847893 (test)](http://test.lobid.org/resources/HT007847893.json).

**Comment by acka47** [comment]
Something goes wrong processing the death date of Pindaros. From the [source]():

```xml
<datafield tag="104" ind1="a" ind2="1">
  <subfield code="p">Pindarus</subfield>
  <subfield code="d">v522-v445</subfield>
  <subfield code="9">(DE-588)118594427</subfield>
</datafield>
```

The current resulting JSON contains the following:

```json
"dateOfBirth": "-0522",
"dateOfDeath": "-0044",
"id": "http://d-nb.info/gnd/118594427",
"label": "Pindarus",
```

**Comment by ChristophEwertowski** [comment]
Fixed. See http://test.lobid.org/resources/HT007847893.json.

**Comment by acka47** [comment]
+1

**Comment by ChristophEwertowski** [comment]
Argh. `gYear` values have to have four digit values (https://www.w3.org/TR/xmlschema-2/#gYear). So the build doesn't complete. 
I propose that we remove the `referenceType` from the context. On the other hand, if we want to use more GND data, we have to add the 0's again and show it differently in the frontend because they use the `gYear` datatype (see http://d-nb.info/gnd/118594893/about/lds).
Anyway, now the 0's are removed (http://test.lobid.org/resources/HT007847893.json).

**Comment by acka47** [comment]
In an offline discussion we decided to re-introduce the leading zeros to be conformant with the GND ontology.

**Comment by ChristophEwertowski** [comment]
The leading zeros are back again, see for example: Apollinaris in [TT002001274](http://test.lobid.org/resources/TT002001274.json) or Pindaros (BC) in [HT007847893](http://test.lobid.org/resources/HT007847893.json).

**Comment by acka47** [comment]
Thanks! +1

**Comment by aquast** [comment]
Recently we are not sure anymore, what the customers Use Case for filing the issue was. See https://jira.hbz-nrw.de/browse/EDOZWO-637 
The only thing I can identify as unsolved is sorting should be for instance: "Castor, von Karden (ca Mitte 4. Jhdt.)" not "Castor (ca. 4. Jhdt.), von Karden".
It seems to be an issue of using lobid for 3rd. party systems, we have had formerly no knowledge of. Therefore I presume we will close the issue in our ticket system asap and will delegate it to lobid

**Comment by ChristophEwertowski** [comment]
@aquast But in the jira ticket it is stated like this: 
```
Soll:
Schlagwortfolge

    Castor, von Karden (ca. Mitte d. 4. Jh.), Biographie, Elektronische Publikation
``` 
and
```
Soll:
Otto, von Rheineck (-1150), Theaterstück, Online-Publikation 
```
Which sorting is right, which is wrong?

**Comment by acka47** [comment]
Since September 11th, users of the API have everything they need for displaying the information is needed.

From http://lobid.org/resources/CT001004829.json:

```json
{
   "componentList":[
      {
         "dateOfDeath":"1150",
         "id":"http://d-nb.info/gnd/138460604",
         "label":"Otto, von Rheineck",
         "source":{
            "id":"http://d-nb.info/gnd/7749153-1",
            "label":"Gemeinsame Normdatei (GND)"
         },
         "type":[
            "Person"
         ]
      },
      {
         "label":"Theaterstück",
         "type":[
            "SubjectHeading"
         ]
      },
      {
         "label":"Online-Publikation",
         "type":[
            "SubjectHeading"
         ]
      }
   ],
   "type":[
      "ComplexSubject"
   ]
}
```

From http://lobid.org/resources/HT017260117.json:

```json
{
   "componentList":[
      {
         "dateOfBirthAndDeath":"ca. Mitte d. 4. Jh.",
         "id":"http://d-nb.info/gnd/129877727",
         "label":"Castor, von Karden",
         "source":{
            "id":"http://d-nb.info/gnd/7749153-1",
            "label":"Gemeinsame Normdatei (GND)"
         },
         "type":[
            "Person"
         ]
      },
      {
         "label":"Biographie",
         "type":[
            "SubjectHeading"
         ]
      },
      {
         "label":"Elektronische Publikation",
         "type":[
            "SubjectHeading"
         ]
      }
   ],
   "type":[
      "ComplexSubject"
   ]
}
```

Note that in `dateOfBirth` and `dateOfDeath` you will only find values of datatype http://www.w3.org/2001/XMLSchema#gYear (see the [JSON-LD context](http://lobid.org/resources/context.jsonld)). `dateOfBirthAndDeath`is used for entries where a concreteyear can't be given (e.g. "ca. Mitte d. 4. Jh.", "ca. 6. Jh" etc.).

**Comment by aquast** [comment]
At edoweb we rely recently on the subjectAltLabel. For lobid.org/resources/CT001004829.json it looks fine now. Nevertheless we have repeated date-information here:   lobid.org/resources/HT017260117.json

"subjectAltLabel" : [ "Heiliger (ca. Mitte d. 4. Jh.)", "Sanctus (ca. Mitte d. 4. Jh.)", "von Karden (ca. Mitte d. 4. Jh.)" ],

**Comment by acka47** [comment]
`subjectAltLabel` is not intended for display but for search so that I don't see any problem with the repeated date information. (The dates are also repeated in the source data, see `952` in http://lobid.org/hbz01/HT017260117.)  As it contains all of the variant names for all subjects in the component list, the `subjectAltLabel` list can become very long, see e.g. http://lobid.org/resources/HT018974017.json. Do you really display this list to the end user?

**Comment by ChristophEwertowski** [comment]
In edoweb they are displayed, see "Freie Schlagwörter" at https://www.edoweb-rlp.de/resource/edoweb%3A7011282.

**Comment by aquast** [comment]
So we have to parse the data given in "componentList".
