### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#586]
There are update problems reported by Edoweb customers. It seems the underlying problem is that the changes missing in the XML Aleph export.

Examples:

- HT019110788 ([source](http://lobid.org/hbz01/HT019110788), [JSON](http://lobid.org/resources/HT019110788.json): Should have "156 Seiten" as extent information (433/extent), see [Aleph](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019110788)
- HT019470495 ([source](http://lobid.org/hbz01/HT019470495), [JSON](http://lobid.org/resources/HT019470495.json)): resource is missing completely ([Aleph](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT019470495))
- HT016630042 ([source](http://lobid.org/hbz01/HT016630042), [JSON](http://lobid.org/resources/HT016630042.json)): Should have „Mülldeponie, Müllentsorgung“  in 710/subjectAltLabel, see [Aleph](http://193.30.112.134/F/?func=find-c&ccl_term=IDN%3DHT016630042)

**Comment by fsteeg** [comment]
I've reindexed this week's updates in the MAB-XML index and this looks good:

http://lobid.org/hbz01/HT019110788
http://lobid.org/hbz01/HT019470495
http://lobid.org/hbz01/HT016630042

Seems to be a general issue with this week's updates. Looking into updating API 1 and 2.

**Comment by fsteeg** [comment]
API 1 reindexed and looks good too:

http://lobid.org/resource/HT019110788
http://lobid.org/resource/HT019470495
http://lobid.org/resource/HT016630042

**Comment by fsteeg** [comment]
And API 2 reindexed, looks good:

http://lobid.org/resources/HT019110788
http://lobid.org/resources/HT019470495
http://lobid.org/resources/HT016630042

The missing updates were probably caused by yesterday's server issues, which were caused by a missing network mount (correct, @dr0i?), which was originally caused by the migration to our new  data center.

@dr0i: leaving this open for your information and review/further analysis. One detail, not sure how relevant it is: I got `build error` when indexing the first of this week's updates (`20171007-20171008`).

**Comment by acka47** [comment]
API 2.0 now also is up to date. Very good.

**Comment by aquast** [comment]
Hi semweb,

will this be a workaround for the resources the edoweb customer identified as missing or does it mean all resources are reindexed now? How could we prevent stuation like this in future?

**Comment by dr0i** [comment]
<tl;dr>Cause not clear. Never happened before. Runs smoothly since. hbz/lobid#354 will cope with such a problem.</tl;dr>

From /var/log/syslog:
> Oct 10 02:30:01 weywot1 CRON[62681]: (hduser) CMD (DATE=$(date "+%Y%m%d-%H%M"); cd git/hbz-aleph-dumping/bin; bash -x daily-hbz-aleph.sh > logs/daily-hbz-aleph.sh.$DATE.log 2>&1)

=> job starteded correctly at 02:30 , _but_:

http://lobid.org/download/dumps/DE-605/mabxml/
(=>  DE-605-aleph-update-marcxchange-20171009-20171010.tar.gz 2017-10-10 08:25   19M  )

shows that the file was ready _much_ later as expected (08:25, i.e. 6h). Following ETL-programs are scheduler beginning with 02:30 +1h (for http://lobid.org/hbz01) or +2h for lobid-api2.0, not +6h.

Still don't know the _cause_, though. Maybe a slow connection to aleph-DB.
This is a precedent. it has never happened before.
However, switching to jenkins (hbz/lobid#354) we will *event-scheduling* our workflow so that that everything is chained and in this case the ETL-processes would have begun at last at 8:25 and eventually finished a littl ebit later successfully.

**Comment by dr0i** [comment]
A note to this:
Just remembered that we had several issues on 10.10.2017, as @fsteeg noted already in https://github.com/hbz/lobid-resources/issues/586#issuecomment-335840358: Lobid-website was down and the load-balancer didn't work. Another incidence was a malfunctioning `nfs-mount` on gaia. Interestingly this bad nfs-mount must have been the cause of the fact that I couldn't start elasticsearch (it showed up as a process but it just seemed to hang. `strace` output was just one line). Since the remount of this nfs-mount elasticsearch started normally.
So the conclusion must be:
- we had had a major network problem effecting multiple server
- avoid `nfs-mounts` 

Opened hbz/lobid#355 to get rif of the nfs-mount.
