### ISSUE TITLE
Use MAB 590-599 for hasSuperordinate

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#702]
For "unselbstständige Werke" MAB 590-599 contains information about the superordinated resource.

**Comment by ChristophEwertowski** [comment]
Relates to https://github.com/hbz/lobid-resources/issues/508.

**Comment by ChristophEwertowski** [comment]
Deployed to test, see `isPartOf` in [TT002303245](http://test.lobid.org/resources/TT002303245.json) (label consists of MAB 590 and 592). MAB 591 (creator of source), MAB 593 (edition of source in personal examination), MAB 594 (place of source), MAB 595 (year of source), MAB 597 ("Gesamttitel" of source) and MAB 598 (note of source) aren't used as the information should be in the superordinated resource.

**Comment by ChristophEwertowski** [comment]
MAB 599 can be used 20 times according to the "Feldhilfe" but I couldn't find an example for it. Not covered are resource like HT00784776 which have two numberings. Also all those cases in the test resources don't have MAB 599, e.g. an id field.

**Comment by acka47** [comment]
We use `containedIn` for the relation between an `Article` or another "unselbständiges Werk" and the resource it is part of. The `containedIn` information is already part of the data, see e.g. http://lobid.org/resources/TT002303245.json:

```json
{
  "containedIn":[
    {
      "id":"http://lobid.org/resources/HT001967154#!",
      "label":"lobid Ressource"
    }
  ]
}
```

We should _not_ start using the `isPartOf` relation for this. However, the PR brings another improvement with it, using the actual title of the containing resource instead of the placeholder "lobid Ressource", see http://test.lobid.org/resources/TT002303245.json:

```json
{
  "containedIn":[
    {
      "id":"http://lobid.org/resources/HT001967154#!",
      "label":"Aufstieg und Niedergang der römischen Welt, 1. Von den Anfängen Roms bis zum Ausgang der Republik"
    }
  ]
}
```

We should keep this but as said not add any `isPartOfrelation forunselbständige Werke.

**Comment by acka47** [comment]
@dr0i I am not sure whether we can just remove some parts of the morph changes in https://github.com/hbz/lobid-resources/pull/901/commits/3f28041ea867b7ac33af9f8b0a8753774f8eedad to achieve the outcome I described in the last commentary...

**Comment by dr0i** [comment]
Ignoring @acka47 comment 

> We should not start using the isPartOf relation for this

is not the right way of resolving ;)
The "isPartOf"."hasSuperordinate" should be removed.
