### ISSUE TITLE
Add criteria for types Map, Article and PublishedScore

### ISSUE THREAD

**Issue by ChristophEwertowski** [hbz/lobid-resources#703]
Originating from #628.
- [x] [BT000003404 (MAB)](http://lobid.org/hbz01/BT000003404): Map in a collection of maps. @acka47 : Shouldn't `Map` be a publication type rather than medium? We have `Print` already in the json and a map can also appear online or on microfiche.   
- ~~HT013577568: Part of a volume. Not exactly an Article because it didn't appear in a journal. In German it is called "Beitrag" (for example in the bibliography of the RUB) but also could be named chapter.~~ In Aleph it isn't separated so we can cross this off. Especially since it isn't probably important to the user.
- [ ] [HT013925945 (MAB)](http://lobid.org/hbz01/HT013925945): Article which isn't typed as such (missing t in MAB 051). We could use MAB 525 (Herkunftsangabe) and MAB 590-599 (Segment Herkunft (Quelle) unselbstständig erschienener Werke) for it.
- [ ] [HT016608165 (MAB)](http://lobid.org/hbz01/HT016608165): Part of a music CD, should be "Musikalia". We could use MAB 503a (Deutsche Übersetzung bzw. Hinweise auf die musikalische Form -   a     = Hinweis auf die musikalische Form und/oder Besetzung), MAB 516 (Angaben über Schrift, Sprache und Vollständigkeit der Vorlage und musikalische Notation) or specific roles from the 100s. Note: At the moment we use `PublishedScore` for all musical works not only scores.

**Comment by acka47** [comment]
> shouldn't Map be a publication type rather than medium? We have Print already in the json and a map can also appear online or on microfiche.

You are right that the medium and type information is not ideal. However, people can combine different entries from  the medium facet, e.g. [online maps](http://lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMap%2Chttp%3A%2F%2Frdaregistry.info%2FtermList%2FRDACarrierType%2F1018%2CAND&aggregations=medium.id), [maps that are books and reference works](http://lobid.org/resources/search?medium=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FMap&t=Book%2CReferenceSource%2CAND&aggregations=type) so that this is not such a big problem. (A historical note: When we added factes in 2014 we adopted the approach from DigiBib where already a lot of thought had been put into it. See the wiki page at https://wiki1.hbz-nrw.de/display/SEM/Facetten+ueber+hbz01-Daten.)

However, feel free to open a ticket where we move `Image` and `Map` from medium to type.

**Comment by ChristophEwertowski** [comment]
Assigning @acka47 to answer if it is worth to cover points three and four.

**Comment by TobiasNx** [comment]
> * [ ]  [HT013925945 (MAB)](http://lobid.org/hbz01/HT013925945): Article which isn't typed as such (missing t in MAB 051). We could use MAB 525 (Herkunftsangabe) and MAB 590-599 (Segment Herkunft (Quelle) unselbstständig erschienener Werke) for it.

This is now article with ALMA Marc: https://lobid.org/resources/990124738110206441

But I added these possible criterias in the article isse: https://github.com/hbz/lobid-resources/issues/1314

> [HT016608165 (MAB)](http://lobid.org/hbz01/HT016608165): Part of a music CD, should be "Musikalia". We could use MAB 503a (Deutsche Übersetzung bzw. Hinweise auf die musikalische Form - a = Hinweis auf die musikalische Form und/oder Besetzung), MAB 516 (Angaben über Schrift, Sprache und Vollständigkeit der Vorlage und musikalische Notation) or specific roles from the 100s. Note: At the moment we use `PublishedScore` for all musical works not only scores.

MusicalRecording was introduced with issue: #1685 

Therefore closing the ticket.
