### ISSUE TITLE
HT019582722 has empty objects

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#718]
Resolving #713 results in HT019582722 being indexed . But the web app has problems to render it: http://lobid.org/resources/HT019582722.

**Comment by fsteeg** [comment]
Root cause of this are empty objects in `isPartOf` and `publication`, see http://lobid.org/resources/HT019582722.json. I've seen the same in `subject` the other day. Fixed the null pointer in https://github.com/hbz/lobid-resources/pull/721 to avoid the error, but details do not display correctly due to the empty object. Should additionally be fixed on the data level.

**Comment by fsteeg** [comment]
Fix to avoid error on page load fixed and deployed, underlying data issue persists and causes wrong details, see http://lobid.org/resources/HT019582722

**Comment by fsteeg** [comment]
Original issue fixed, remaining problem already mentioned in https://github.com/hbz/lobid-resources/issues/569, closing.
