### ISSUE TITLE
Take into account MARC relator codes in RDA entries

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#72]
Moved here from https://github.com/lobid/lodmill/issues/759. Sub-issue of https://github.com/hbz/lobid/issues/161, see https://github.com/hbz/lobid/issues/161#issuecomment-161566116.

We just have to take the code from subfield 4 in the 1*\* and 2*\* fields and append it to `http://id.loc.gov/vocabulary/relators/` to get the relator code for the respective entry. Default entry (at least for person) is `aut` but for now we will continue using `dct:creator`.

Examples:

http://lobid.org/resource/HT018772877, [source](http://beta.lobid.org/hbz01/HT018772877) (snippet):

``` xml
<datafield tag="100" ind1="b" ind2="1">
  <subfield code="p">Klein, Volkmar</subfield>
  <subfield code="4">edt</subfield>
  <subfield code="3">Herausgeber</subfield>
  <subfield code="9">(DE-588)174630727</subfield>
</datafield>
```

http://lobid.org/resource/HT018776405, [source](http://beta.lobid.org/hbz01/HT018776405) (snippet):

``` xml
<datafield tag="200" ind1="b" ind2="1">
  <subfield code="k">Theater im Pfalzbau</subfield>
  <subfield code="4">isb</subfield>
  <subfield code="3">Herausgebendes Organ</subfield>
  <subfield code="9">(DE-588)301289-X</subfield>
</datafield>
```

https://lobid.org/resource/HT018781534, [source](http://beta.lobid.org/hbz01/HT018781534) (snippet):

``` xml
<datafield tag="100" ind1="-" ind2="1">
  <subfield code="p">Schroeder, Hermann</subfield>
  <subfield code="d">1904-1984</subfield>
  <subfield code="4">cmp</subfield>
  <subfield code="3">Komponist</subfield>
  <subfield code="9">(DE-588)118823442</subfield>
</datafield>
```

https://lobid.org/resource/HT018782520, [source](http://beta.lobid.org/hbz01/HT018782520) (snippet):

``` xml
<datafield tag="104" ind1="a" ind2="1">
  <subfield code="p">Heitmann, Michaela</subfield>
  <subfield code="d">1969-</subfield>
  <subfield code="4">art</subfield>
  <subfield code="3">Künstler</subfield>
  <subfield code="9">(DE-588)142552739</subfield>
</datafield>
```

**Comment by ChristophEwertowski** [comment]
Looked at the 5021 files of the small test (test.tar.bz2) to find some examples for the functional review. The only file where changes can be seen is: [HT018939763 (test server)](http://test.lobid.org/resources/HT018939763) / [HT018939763 (production)](http://lobid.org/resources/HT018939763). Other files which have the subfield but aren't converted because of the missing role in the morph are: HT018770176, HT019093814, HT018786244 and HT018924091 (all /pbl or publisher), HT018889713 (/oth or other) and HT018889713 (/isb or issuing body). I don't know if there are more files which have the subfield in the folder of all Xml files but I doubt it. @acka47 : You can "review" it now.

**Comment by acka47** [comment]
> . Other files which have the subfield but aren't converted because of the missing role in the morph are: HT018770176, HT019093814, HT018786244 and HT018924091 (all /pbl or publisher), HT018889713 (/oth or other) and HT018889713 (/isb or issuing body)

`pbl` comes from field `677` and thus isn't covered. `isb`comes from 204 and thus should be covered according to https://github.com/hbz/lobid-resources/commit/9f31e5c6454106f3b4f61a2d70a3288deab32a94#diff-9cd7dc3a9e57c8e575367094c6f3306bR1074. `oth` should also be covered.

I wonder why the roles have to be mentioned in the morph at all. We could just take the code from subfield `4` and put it behind the namespace id `http://id.loc.gov/vocabulary/relators/`...

**Comment by ChristophEwertowski** [comment]
The files mentioned above have the roles in the subfield 4 of the 100s and 200s datafields. We can't take the roles only from the subfield 4 because there are next to none entries.

**Comment by acka47** [comment]
> The files mentioned above have the roles in the subfield 4 of the 100s and 200s datafields. 

As I said above, this is not the case for [HT018770176](http://lobid.org/hbz01/HT018770176), [HT019093814](http://lobid.org/hbz01/HT019093814), [HT018786244](http://lobid.org/hbz01/HT018786244) and [HT018924091](http://lobid.org/hbz01/HT018924091) where `pbl` is in subfield `4` of 677.

I guess, we can leave out `oth` in the conversion as it doesn't add useful information.

However, I think we should transform `isb` (i.e. add it to the morph) and show it as "Herausgeber/in" in the labels.json (similar to `edt`).

**Comment by ChristophEwertowski** [comment]
Added the role "issuing body" with the label "Herausgeber" to the files. @fsteeg : I suppose, since it's a new role, although with an already existing label, it isn't shown in the gui, is it? At least I can't see it with a new test index.

**Comment by fsteeg** [comment]
Not sure where it's supposed to be in the data.

Also, you can always use the link in the upper right corner of the details table:

http://test.lobid.org/resources/HT018770176

to check if it's in the JSON:

http://test.lobid.org/resources/HT018770176?format=json

In general I'd hope that a new role should show up in the UI automatically.

**Comment by acka47** [comment]
This is the file with the `isb` role: http://test.lobid.org/resources/HT018889713. I can't find it in the RDF.

**Comment by ChristophEwertowski** [comment]
Improved the regular expression so that issuing body is now shown as "Herausgeber/in" ([example (test)](http://test.lobid.org/resources/HT018889713) / [example (production](http://lobid.org/resources/HT018889713)). But now the responsibility statement isn't shown anymore although I didn't changed anything about it (see example above). @fsteeg : Is the responsibility statement only shown if there is no "Herausgeber"?

Also the issuing body can now be seen in the frontend but can't be found in the json file ([json of the same example](http://test.lobid.org/resources/HT018889713?format=json)). Does anybody have an idea what the reason for this is?

**Comment by fsteeg** [comment]
Latest changes were not deployed to test system, updated it: http://test.lobid.org/resources/HT018889713

**Comment by acka47** [comment]
Looks good to me. +1

**Comment by dr0i** [comment]
Deployed to stage.

**Comment by acka47** [comment]
Just noticed that `art` ("Künstler/in", example http://lobid.org/resources/HT018782520) and `cmp` ("Komposition", example lobid.org/resources/HT018782520) aren't taken into account in the transformation yet. Anyway, +1 and please deploy to production. I opened another issue for these two at #336.
