### ISSUE TITLE
Example API 2.0 files

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#79]
To give @dr0i some more guidance for working on [API 2.0 issues](https://waffle.io/hbz/lobid?label=API%202.0) it would be nice for him to have some examples of how the desired structure should look like.

**Comment by acka47** [comment]
I managed to create three example files. They probably won't work as test files as I have probably made minor mistakes or might have forgot some changes but in general they should provide good guidance:

- [CT003012479.json](https://gist.github.com/acka47/d0f6fcf2766bb5894f815cf056665e95)
- [HT013304490.json](https://gist.github.com/acka47/7fd1249ff33f08436c7d26f70b32c04c)
- [TT002234459.json](https://gist.github.com/acka47/33ac6792c71f3441f8b875f19b46e9f3)

Note that this also is not the final state we should have in API 2.0. One problem with TT002234459.json I described in https://github.com/hbz/lobid-resources/issues/8#issuecomment-214744018.

**Comment by acka47** [comment]
Where needed, I adjusted the examples according to https://github.com/hbz/lobid-resources/issues/38#issuecomment-259084607, see the second revisions of the files:


- [CT003012479.json](https://gist.github.com/acka47/d0f6fcf2766bb5894f815cf056665e95/c3f358c4e8d7473c4d5f3a49ba663c0b53792e70)
- [TT002234459.json](https://gist.github.com/acka47/33ac6792c71f3441f8b875f19b46e9f3/58c002f1dd1d70c4828512fb87cc1416e72e4985)

**Comment by dr0i** [comment]
In the mentioned CT003012479 there is a `dateOf` property as part of a person entity. At the moment we use these life dates only for subjects (field `9[01234][27]-[-12].d`). Should we want to take life dates for person entities which are no subjects also into account we should make a new issue.

**Comment by acka47** [comment]
I removed the dates from the example.

**Comment by dr0i** [comment]
Compared your files with the staging index. Difference:
In  CT003012479 you listed 14216075X two times (quote right, as in the source http://lobid.org/hbz01/CT003012479 this person is also mentioned in field 800 as "Sprecher") whereas in http://test.lobid.org/resources/CT003012479#! there is only one mentioning of her. The two appearances of the person seems a bit superflous to me, though, because she is first roled as an `actress` and then as a `contributor` whereas , I think, every agent in the `contribution`-list is implicitly a contributor.

At the moment the 8xx-fields are not  analyzed thus the role ("Sprecher") is ignored. I assume that that leads to the merged one mentioning of the person. 
What shall we do? Take roles of 8xx-fields also into account? The person would then appear one time with two roles: actress and speaker.

**Comment by acka47** [comment]
Generally, I think it is ok to only list a person once when it is mentioned twice in the source but one role is just `Contributor`. I also agree that we shouldn't take into account 8xx fields.

But I don't think it is ok to list two roles in one `contribution` object. If a person has two roles in a work (e.g. "Sprecher" and "Darsteller" these are actually two contributions with different roles but not one contribution covering two roles.

**Comment by dr0i** [comment]
These example files are a bit out of date, but as @acka47 just said we won't update these examples. I compared them with the staging data and find them fitting.
So +1 for me for closing, assigning @acka47 .

**Comment by acka47** [comment]
> But I don't think it is ok to list two roles in one `contribution` object. If a person has two roles in a work (e.g. "Sprecher" and "Darsteller") these are actually two contributions with different roles but not one contribution covering two roles.

I posted this question to the Bibframe list and Ray Denenberg just confirmed what I said. Quoting Ray:

> If you want to list two roles, e.g. “illustrator” and “author” for the
> same person, the rule is, declare two separate Contribution resources.  
> Two or more role statements within the same Contribution resource should
> occur only because you want to provide two different representations
> (e.g. two different URIs) for the same role.

**Comment by acka47** [comment]
Closing.
