### ISSUE TITLE
Missing resource in data 2.0

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#80]
Missing:

http://lobid.org/resources/TT002234858

OK:

http://lobid.org/resource/TT002234858
http://lobid.org/hbz01/TT002234858

**Comment by fsteeg** [comment]
Resource was created 20040312 and updated 20160514, so the fact that it's missing should not be due to an issue with the updates. I checked the logs for the time it was updated and there's nothing unusual. Sounds similar to #69 (created 20121008).

Maybe some resources are silently skipped during the transformation?

**Comment by dr0i** [comment]
It's a mapping problem `org.elasticsearch.index.mapper.MapperParsingException: failed to parse [note]`:  the [field `note` is defined as string](https://github.com/hbz/lobid-resources/blob/c2e6f36fb76164f0c212ac31ceedd6cfc35f1049/src/main/resources/index-config.json#L517), but for `TT002234858` the `note` field is an _id_: `"id":"http://www.stk.rlp.de"`.
Interestingly, in Api1.0 the field  is defined to have two properties:

    properties: {
    @value: {
        type: string
    }
    @id: {
        type: string
    }
    }... 
so that it's possible to have a `note.@id` field and a `note.@value`.

Possible solutions:

- create subfields for note, e.g. "value" and "id"
- add another property which expects a URI as note to discriminate it from the note-as-plain-string
- prefix something in the data when a URI is found for `note` like "Siehe $URI" to make it a string

I understand that we want to keep the structure of the data in API 2.0 as simple as possible and thus don't want to have subfields for `note` discriminating string and ids? (I tend to prefer the second proposal but could think that the last proposal makes more "sense" (also expecting that there are not many URIs as `notes`).

What do you thing @fsteeg  @acka47 @jschnasse ?

**Comment by fsteeg** [comment]
To me the third proposal sounds good. Just a URI as `note` seems weird.

See also https://www.w3.org/TR/skos-reference/#notes

**Comment by dr0i** [comment]
Maybe `rdf:seeAlso` would be of good:

    The RDF Schema (RDFS) specification defines a term called rdfs:seeAlso which relates a resource to another resource "that might provide additional information about the subject resource." 

I'am not fully satisfied with the solution of prefixing a string because the string is language dependent (German) while these `notes` may be in other languages.
However the main issue should be fixed with the commit.

**Comment by dr0i** [comment]
Deployed to production , closing.
