### ISSUE TITLE
Dewey-label fallback

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#814]
If the specific notation is missing in our dewey-concordance (like ` 491.4682421` in our test resource `HT019578856`) one could use a fallback to choose the `491` as label - in this case `Ostindoeuropäische und keltische Sprachen`.

**Comment by dr0i** [comment]
@ChristophEwertowski note, I created a new label `enrichment`, we can label our issues with this and can then easily filter all issues having something to do with `enrichment`.

**Comment by ChristophEwertowski** [comment]
I think that it only makes sense if we use it for all `enrichment` issues. Dewey issues are normally fixed too fast that multiple issues could be put under this tag. We can try it out.

**Comment by ChristophEwertowski** [comment]
[Query](http://lobid.org/resources/search?q=_exists_%3Asubject.notation+AND+subject.source.id%3A%22http%3A%2F%2Fd-nb.info%2Fgnd%2F4149423-4%22+NOT+_exists_%3Asubject.label) for resources with `notation` and Dewey `source.id` but no `label`: ~56.600 resources.

**Comment by ChristophEwertowski** [comment]
There are 7680 different notations which lead to the resources with Dewey `notation` but without `label`. Not only long notations are affected but short ones like `004.01` ("Informatik--Philosophie, . . ."), too. 
[missingNotations.txt](https://github.com/hbz/lobid-resources/files/1970794/missingNotations.txt)

**Comment by ChristophEwertowski** [comment]
Actually there are 6840 different notations.
[missingNotations2.txt](https://github.com/hbz/lobid-resources/files/1984387/missingNotations2.txt)

**Comment by ChristophEwertowski** [comment]
I filtered the MARC code of the DNB. If I understood the MARC xml right there are no labels which aren't already in our Dewey file.

**Comment by ChristophEwertowski** [comment]
Finally it's done. If there is no label for the notation, the label of the main class (the first three digits) will be used for showing labels. Look in [HT015455455 (production, json)](http://lobid.org/resources/HT015455455.json) / [HT015455455 (test, json)](http://test.lobid.org/resources/HT015455455.json) for the Dewey subjects. In production often MAB 705a1.c (short notation) is used for the notation instead of MAB 705a1.a (full notation). Because of this wrong labels are shown. Still the full notation will be presented. 

The reason for using only the main classes for labels is this: Notations can be put together like `338.76629220904` which can be translated to 338.76 (Unternehmen nach Industrie), 629.22 (Fahrzeugarten), 0 (Allgemeine Werke) and 904 (Allgemeine Darstellung von Ereignissen). This task is too difficult for computers so we can't do it automatically. Now people get the clue what the resource mainly is about: Production (of cars). And then they can put together the rest of the meaning.

**Comment by acka47** [comment]
+1

**Comment by acka47** [comment]
This is not deployed yet is it? I just stumbled over this entry that seems to have problems with DDC: http://lobid.org/resources/HT008815963 In `700` it reads:

```xml
<datafield tag="700" ind1="-" ind2="1">
   <subfield code="a">406120</subfield>
</datafield>
```

In the JSON it looks like this:

```json
{
  "subject":[
    {
      "label":"Epistemologie, Kausalität, Menschheit",
      "notation":"120",
      "source":{
        "id":"http://d-nb.info/gnd/4149423-4",
        "label":"Dewey-Dezimalklassifikation"
      }
    },
    {
      "label":"Organisationen und Management",
      "notation":"406",
      "source":{
        "id":"http://d-nb.info/gnd/4149423-4",
        "label":"Dewey-Dezimalklassifikation"
      }
    }
  ]
}
```

it doesn't look right that the `120` is listed here. @ChristophEwertowski, just ignore this comment if it does not occur after deploying the PR to this issue.

**Comment by ChristophEwertowski** [comment]
@acka47 : A library specific notation is seen as a Dewey notation, see newly opened ticket #841.
