### ISSUE TITLE
Too many performers

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#878]
See e.g. HT017608824 ([source](http://lobid.org/hbz01/HT017608824), [lobid](http://lobid.org/resources/HT017608824)). There are two persons with role `prf` in the JSON that don't have indicator2=e in the source data and thus shouldn't have role "performer".

Snippet from the source:

```xml
<datafield tag="100" ind1="-" ind2="1">
  <subfield code="p">Gounod, Charles</subfield>
  <subfield code="d">1818-1893</subfield>
  <subfield code="9">(DE-588)118718312</subfield>
</datafield>
...
<datafield tag="104" ind1="b" ind2="1">
<subfield code="p">Barbier, Jules</subfield>
<subfield code="d">1825-1901</subfield>
<subfield code="b">[Text]</subfield>
<subfield code="9">(DE-588)119309998</subfield>
</datafield>
```

JSON:

```json
{
  "contribution":[
    {
      "agent":{
        "id":"http://d-nb.info/gnd/118718312",
        "label":"Gounod, Charles",
        "type":[
          "Person"
        ]
      },
      "role":{
        "id":"http://id.loc.gov/vocabulary/relators/prf",
        "label":"Interpret/in"
      },
      "type":[
        "Contribution"
      ]
    },
    {
      "agent":{
        "id":"http://d-nb.info/gnd/119309998",
        "label":"Barbier, Jules",
        "type":[
          "Person"
        ]
      },
      "role":{
        "id":"http://id.loc.gov/vocabulary/relators/prf",
        "label":"Interpret/in"
      },
      "type":[
        "Contribution"
      ]
    }
  ]
}
```

**Comment by ChristophEwertowski** [comment]
Deployed to test. See `Debussy` and `Banville` at [HT016608165 (production, json)](http://lobid.org/resources/HT016608165.json) / [HT016608165 (test, json)](http://test.lobid.org/resources/HT016608165.json) which are also declared to be performers although they are creator and contributor. The problem was a regular expression which only asked for any of the MAB 100s in the resources to have an `ind1="e"` but not specifically the one with which the macro is used. (Your mentioned resource worked also in my test branch but they aren't needed to show the effect of the changes.)

Also corrected a regular expression for honorees.
