### ISSUE TITLE
URN being an URL => MapperParsingException => drop document

### ISSUE THREAD

**Issue by dr0i** [hbz/lobid-resources#88]
An`urn` beeing an `id` (while expecting a value) breaks ES document parsing with `MapperParsingException`. Thus dropping the doc in whole.
55 docs affected as of lobid-gaia.log.2016-07-02:
`grep MapperParsingException  lobid-gaia.log.2016-07-02 | grep urn | wc -l` : 55

Example: http://lobid.org/resources/HT018956414

**Comment by ChristophEwertowski** [comment]
Sub-issue of #482. The definition of the field from our vocabulary: 

> The URN must be stated as a string not as URI, thus identifying the identifier itself and not the resource that is identified by the URN.

There are URLs which contain non-URN-identifer (http://lobid.org/hbz01/HT019322941, field 552) but also URLs which contain the URNs (http://lobid.org/hbz01/HT019054687). The latter can be extracted because they start with `urn:nbn:de` if they describe libraries and publishers who work with the DNB. To be sure to get all URNs we should search for `urn:`. The former could be put into `note` or probably `sameAs`.

**Comment by ChristophEwertowski** [comment]
Deployed the changes to the test index. The resources are visible again because the `urn` fields contain URNs ([example (production)](http://lobid.org/resources/HT019054687) / [example (test)](http://test.lobid.org/resources/HT019054687)). If 552b1 contains strings without `urn:` the contents are put into `hasVersion` because often there are other ids connected with a resolver (or misplaced DOIs). 
Note: There are also MAB `655[gu]1.a` which can contain URNs. But at the test set these URNs where also in 552b1.a so to not blow up the code I didn't refered to these fields.

**Comment by acka47** [comment]
+1
