### ISSUE TITLE
Agent label is array

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#953]
See last contribution (`2176207-7`) in http://lobid.org/resources/HT019740439.json

Caused https://github.com/hbz/nwbib/issues/449

**Comment by dr0i** [comment]
This is because the gnd-id `http://lobid.org/gnd/2176207-7` is used to encode also "natureOfContent" - which doesn't make sense.  Now, this gnd-ID is also (correctly) used as "Contributer" (and "subject), but thus has been given two labels: one originating from 064 (falsly stating "Ausstellungskatalog" as label), the other label from 200 resp. 902 (correctly, the same label for bot entries).

I would want to see this corrected in the hbz01-catalog, no @acka47 ?

**Comment by acka47** [comment]
Yes, this has to be corrected in the catalogue. Will trigger verbundgruppe. :wink:

**Comment by acka47** [comment]
Just sent an email to verbund.

**Comment by acka47** [comment]
This is now fixed in hbz01. Closing.
