### ISSUE TITLE
Adjust URIs for controlled value lists from RDA

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-resources#97]
Holds for all values with `rdvocab.info` in them.

For example:

http://rdvocab.info/termList/RDAproductionMethod/1010
http://rdvocab.info/termList/RDACarrierType/1018
http://rdvocab.info/termList/RDACarrierType/1010

**Comment by acka47** [comment]
NWBib probably has to be adjusted when doing this.

**Comment by ChristophEwertowski** [comment]
The first example is dealt with in #74.

**Comment by acka47** [comment]
From https://github.com/hbz/lobid-resources/issues/74#issuecomment-272392968:

> I just noticed that the actual URI is `http://rdaregistry.info/termList/RDAproductionMethod/1010` as is written in the HTML and in the RDF (`curl -L -H "Accept: text/turtle" http://rdaregistry.info/termList/RDAproductionMethod`).

**Comment by acka47** [comment]
By now the old namespace (`http://rdvocab.info/termList`) redirects to the new one (`http://rdaregistry.info/termList`).

**Comment by ChristophEwertowski** [comment]
After talking to acka47 also removed workManifested because it's deprecated and only used in labels.json and neither morph nor context.json. Also expanded .gitignore like dr0i in [comment](https://github.com/hbz/lobid-resources/pull/173#issuecomment-273473111) suggested to prevent committing unnecessarily input/nt files.
