### ISSUE TITLE
Missing spatial values in staging index

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-resources#990]
Today's staging index has missing spatial values, see e.g.:

http://lobid.org/resources/HT019918339.json
http://stage.lobid.org/resources/HT019918339.json

Seems to be a systematic issue:

https://nwbib.de/search?location=&q=_exists_%3Acoverage+AND+NOT+_exists_%3Aspatial
https://test.nwbib.de/search?location=&q=_exists_%3Acoverage+AND+NOT+_exists_%3Aspatial

**Comment by dr0i** [comment]
Ack. Geo_nwbib-staging wasn't build correctly beacuse of
> ERROR - Can't get wikidata entities·
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException:

Just started the script again. Seems to be temporary issue with wikidata because the SPARQL-query is now succesful.

Good thing also that the index wasn't switched - #975 is doing it's job well!

I think it's good to wait for a new staging index, which will be build at the weekend.

**Comment by acka47** [comment]
>Ack. Geo_nwbib-staging wasn't build correctly beacuse of
>> ERROR - Can't get wikidata entities·
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException:

Wouldn't I make sense to use the results from the previous successful SPARQL query to build the index – which would be the same as to not rebuild the geo index at all?

**Comment by dr0i** [comment]
Hm what would we gain?

As we nowadays rarely change transformation rules AND the inicident happend on wednesday (=> fulldump is the same as the one at the weekend before), this would have build an index _exactly the same_ we already had. So, no gain, just pain (more code more complexity more of it )

 So

**Comment by acka47** [comment]
Sorry, I misunderstood the problem. When talking to @dr0i on the phone I realized that everything worked very well as the problems were only on stage and the sanity checks prevented them propagating to production.

**Comment by dr0i** [comment]
Index healed itself throuhg reindexing at the weekend. Closing.
